### ISSUE TITLE
[Bug] 나무라이브의 차단옵션이 정상적으로 활성화 되지 않습니다.

### ISSUE THREAD

**Issue by supers205** [Alex4386/turnoff-namuwiki#20]
## 환경 (Tell me the environments when the bug occurs)
* [X] Google Chrome (or Chromium)  
* [ ] Mozilla Firefox
* [ ] Mozilla Firefox for Android

### 가능하다면 버전을 적어주세요 (What is your browser's version)
*(ex. Mozilla Firefox Developer Edition 69.0b4 64-bit)*
Opera GX LVL1 (core: 63.0.3368.58152)  
based on Chromium/76.0.3809.132

## 버그에 대해 설명해 주세요 (Describe the bug)

설정화면에서 나무라이브 설정을 활성화 하면 다시 꺼집니다.

## 버그를 일으키는 방법에 대해서 설명해 주세요 (Please explain the steps to reproduce)
1. 설정화면에서 나무라이브 설정을 활성화 합니다.  
2. 다시 엽니다.
3. 버그가 발생합니다.  

## 어떻게 동작해야 했나요? (What was the expected behavior?)

나무라이브 설정이 활성화 된 상태로 유지되어야 합니다.

**Comment by Alex4386** [comment]
**Issue Confirmed**

**Comment by Alex4386** [comment]
**Issue Fixed**

**Comment by Alex4386** [comment]
**Closing issue for now**
