### ISSUE TITLE
[Bug] Microsoft Edge beta 79.x 이상에서의 language parsing 관련 오류 발생으로 인한 차단 미작동 버그.

### ISSUE THREAD

**Issue by supers205** [Alex4386/turnoff-namuwiki#23]
## 환경 (Tell me the environments when the bug occurs)
* [x] Google Chrome (or Chromium)  
* [ ] Mozilla Firefox
* [ ] Mozilla Firefox for Android

### 가능하다면 버전을 적어주세요 (What is your browser's version)
*(ex. Mozilla Firefox Developer Edition 69.0b4 64-bit)*

Microsoft Edge Insider Preview 80.0.345.0 DEV 64-bit
(Based on Chromium 80.0.3974.0)

## 버그에 대해 설명해 주세요 (Describe the bug)

나무위키의 일반 버전 접속과 미러 버전 접속, 미러 버전에서의 광고 차단과 나무라이브의 차단이 이루어지고 있지 않습니다.
최근 시드 엔진 (나무위키의 기반 위키 엔진)이 4.16.0로 업데이트 되었는데, 점검 차원에서 접속 방식 변경이나 (나무위키 관계자 측에서 이 확장기능의 존재를 눈치 채고) 잠수함 패치 등의 보이지 않는 방법으로 차단을 우회를 한 것 같습니다.
(일반 버전에서의 나무위키 광고 차단, 검색 엔진 필터링 등의 나머지 부가기능은 정상 작동하고 있습니다.)

## 버그를 일으키는 방법에 대해서 설명해 주세요 (Please explain the steps to reproduce)

1.나무위키 계열 사이트 접속 전에 확장 기능에서 나무위키, 나무위키 미러, 나무라이브 차단을 설정합니다.
2.문제가 발생한 사이트 (나무위키 일반 버전, 나무위키 미러 버전, 나무라이브)에 접속을 시도합니다.
3.위 사이트에서의 차단이 이루어지지 않고 그대로 접속이 이루어집니다.

## 어떻게 동작해야 했나요? (What was the expected behavior?)

나무위키 일반 버전, 미러 버전, 나무라이브의 차단이 이루어져야 합니다.

## 스크린샷 (Screenshots)

![image](https://user-images.githubusercontent.com/41535802/70553583-bdc8a180-1bbe-11ea-82fa-91a927779156.png)
![image](https://user-images.githubusercontent.com/41535802/70553591-c325ec00-1bbe-11ea-8908-36495b0d4dd8.png)
![image](https://user-images.githubusercontent.com/41535802/70553603-ca4cfa00-1bbe-11ea-8d21-c33fd4633713.png)

**Comment by Alex4386** [comment]
**인지하고 있는 증상입니다, 일부 브라우저 업데이트 시 발생하는 버그로 룰셋을 재 설정 (나무위키 차단 설정을 해제후 설정) 하는 경우 해소됩니다.**  
  
Issue 제목을 변경 합니다.

**Comment by Alex4386** [comment]
@supers205 룰셋 설정 이전에 chrome://extensions 접속 바랍니다.

**Comment by supers205** [comment]
commit b37445fbec629b3df50c35a4ac3d78c463f1780a 에서 해결됨.
