### ISSUE TITLE
[Bug] 구글에서 필터링이 안됩니다

### ISSUE THREAD

**Issue by 0x00000FF** [Alex4386/turnoff-namuwiki#24]
## 환경 (Tell me the environments when the bug occurs)
* Google Chrome (or Chromium)  

### 가능하다면 버전을 적어주세요 (What is your browser's version)
*(ex. Mozilla Firefox Developer Edition 69.0b4 64-bit)*

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 Edg/79.0.309.71

## 버그에 대해 설명해 주세요 (Describe the bug)

구글 검색결과에서 나무위키가 필터링 됐던 것 같은데 이번에는 안됩니다.

## 버그를 일으키는 방법에 대해서 설명해 주세요 (Please explain the steps to reproduce)

나무위키에 있을 법한 문서 이름을 구글에 검색

## 어떻게 동작해야 했나요? (What was the expected behavior?)

구글 검색결과에서 나무위키가 없어야 합니다.

## 스크린샷 (Screenshots)

![image](https://user-images.githubusercontent.com/13935811/72960202-40fd2a00-3df0-11ea-82cd-89350a93e4f3.png)

![image](https://user-images.githubusercontent.com/13935811/72960246-5d00cb80-3df0-11ea-99d4-6e93371d7528.png)

![image](https://user-images.githubusercontent.com/13935811/72960290-7dc92100-3df0-11ea-9b61-aecf925d583a.png)

**Comment by Alex4386** [comment]
Google의 검색결과 표시 방식의 HTML이 수정된것 같습니다.

다음 릴리즈에서 수정합니다.

**Comment by Alex4386** [comment]
MS Edge 외의 브라우저 (Mozilla Firefox, Google Chrome) 에서는 구현이 되지 않는 것 같습니다.

현재 MS Edge 설치 중입니다.

**Comment by Alex4386** [comment]
크로미움 엣지에서 재구현에 실패했습니다.
Unable to reproduce in Chromium Edge.

![image](https://user-images.githubusercontent.com/27724108/73336278-b4051580-42b4-11ea-897a-e9642819f243.png)

@0x00000FF 콘솔 정보를 공개해주실 수 있으신가요?

**Comment by Alex4386** [comment]
![image](https://user-images.githubusercontent.com/27724108/73336426-21b14180-42b5-11ea-8177-9572dc4cb536.png)

버전 자체는 동일 한 것 같습니다.

**Comment by Alex4386** [comment]
간헐적으로 발생하는 이슈지만, @0x00000FF 브라우저 업데이트시 설정을 정상적으로 읽어들이지 못하는 버그가 있습니다.

혹여나 콘솔에서 *NAMUWIKI KILL ACTIVE* 문구가 보이지 않는 경우, 해당 속성을 읽어들이지 못한 것이므로, 재 활성화를 시도해 보시기 바랍니다.

해당 사항은 설정 화면에서 *나무위키 광고차단*의 비활성화 후 활성화를 진행 하시면 됩니다.

**Comment by 0x00000FF** [comment]
![image](https://user-images.githubusercontent.com/13935811/73515093-65cc4f80-4437-11ea-9cb9-e78f4da21319.png)

방금 재설치하고 비활성화/활성화를 시도해보았습니다만 여전히 NAMUWIKI KILL ACTIVE는 보이지 않습니다.

버전은 이슈 등록 당시와 동일합니다.

**Comment by Alex4386** [comment]
@0x00000FF 혹시 현재 확장이 최신 버전인지 확인 할 수 있을까요? 0.6.3 에서 간헐적으로 인식이 되지 않는 버그가 확인 되었습니다.

**Comment by 0x00000FF** [comment]
방금 크롬 스토어에서 재설치해봤는데 증상은 여전합니다.

**Comment by Alex4386** [comment]
윈도우 엣지 환경에서 발생하는 것 같네요.
윈도우에서 조만간 테스트 해보겠습니다.

**Comment by Alex4386** [comment]
재구현 불가.

**Comment by Alex4386** [comment]
@0x00000FF 해당 이슈가 df87b3b0034381fd8173057605e65ae7532a29cd 에서 잠재적으로 수정되었을 것으로 추정합니다. 가장 최신 버전 (Github Actions Artifacts 확인 바람) 에서 해당 버그가 재 구현 되는지 확인 부탁드립니다.

**Comment by 0x00000FF** [comment]
![image](https://user-images.githubusercontent.com/13935811/83957318-47250c00-a8a2-11ea-82e2-da5b724d3493.png)

![image](https://user-images.githubusercontent.com/13935811/83957329-602dbd00-a8a2-11ea-928e-9387a55521c1.png)

![image](https://user-images.githubusercontent.com/13935811/83957335-6b80e880-a8a2-11ea-82a1-51f09750a7cb.png)


잠깐 나타났다가 슥하고 사라집니다. 이건 다른 문제인데다 작동이 안되는 이슈는 해결한 듯 하니 여기서는 논할 필요 없을 것 같습니다.

고생하셨습니다!


P. S. 
사족이지만 VPN을 자체구축 해서 쓰면 나무위키가 스스로 거부해주는 이점(?) 이 있는 듯 합니다.
IDC나 통신사쪽 IP를 철저하게 틀어막고 있는 듯 합니다.

![image](https://user-images.githubusercontent.com/13935811/83957351-bf8bcd00-a8a2-11ea-91b8-d49716053021.png)

**Comment by Alex4386** [comment]
Issue가 Resolve 된것으로 추정되므로 Close 하겠습니다.

> 잠깐 나타났다가 슥하고 사라집니다. 이건 다른 문제인데다 작동이 안되는 이슈는 해결한 듯 하니 여기서는 논할 필요 없을 것 같습니다.

이 이슈는 #25 에서 이어서 진행 하겠습니다.
