### ISSUE TITLE
[Bug] 익스텐션 설정화면에서 설정 슬라이더가 즉시 적용되지 않음.

### ISSUE THREAD

**Issue by zeroday0619** [Alex4386/turnoff-namuwiki#25]
## 환경 (Tell me the environments when the bug occurs)
* [ ] Google Chrome (or Chromium)  
* [ ] Mozilla Firefox
* [ ] Mozilla Firefox for Android
* [X] Microsoft Edge (Chromium)

### 가능하다면 버전을 적어주세요 (What is your browser's version)
*(ex. Mozilla Firefox Developer Edition 69.0b4 64-bit)*
Microsoft Edge 80.0.361.62 (공식 빌드)(64-bit)

## 버그에 대해 설명해 주세요 (Describe the bug)
검색 엔진 필터링, 나무위키광고차단, 나무라이브 광고차단 슬라이드가 클릭시 움직이지 않고 클릭후 익스텐션 창을 다시 들어가야 슬라이드가 활성화 상태가 됩니다.

## 버그를 일으키는 방법에 대해서 설명해 주세요 (Please explain the steps to reproduce)
1. Turn off namu wifi 클릭
2. 검색 엔진 필터링, 나무위키광고차단, 나무라이브 광고차단 클릭
3. Turn Off namu wiki 창 나가기
4. Turn off namu wifi 클릭

## 어떻게 동작해야 했나요? (What was the expected behavior?)
검색 엔진 필터링, 나무위키광고차단, 나무라이브 광고차단의 활성화하기 위해 클릭시
슬라이드가 움직여야 됩니다.
## 스크린샷 (Screenshots)
![image](https://user-images.githubusercontent.com/54426648/75511826-c351bd00-5a32-11ea-98b5-46a23433d59a.png)

**Comment by Alex4386** [comment]
@zeroday0619 이슈 하나당 이슈 하나씩,  
1. 슬라이드 반응성 문제는 광고 차단 save data를 가져오는 과정상의 문제로 로직을 개선 할 수 있다면 로직을 개선하면 좋을 것 같습니다. 해결 가능하다면 PR 바랍니다.  
2. 반응이 느린것도 browser extension store 에서 savedata 를 가져오는 과정에서 발생하는 문제로, 해결을 위해서는 로직을 개선해야 합니다.
