### ISSUE TITLE
[Feature Request] 차단 안내 문구 및 링크 추가, 나무위키 차단 해제시 사용자 경험 개선

### ISSUE THREAD

**Issue by kweonsunho** [Alex4386/turnoff-namuwiki#26]
# ISSUE: Feature Request
## 추가를 원하는 기능이 무엇인가요? What kind of feature you are requesting?
- UX (사용자 경험) 개선 (User Experience Enhancements)

## 어떤 기능을 추가했으면 좋을까요? (What feature you are requesting?)
**정확하게 설명해 주세요** (Please explain it in detail)
- [x] 차단 안내 화면에 문구나 링크를 추가 할 수 있으면 좋겠습니다. (링크 추가는 HTML 프로퍼티 추가시 확장스토어 심사에 저촉됨)
- [ ] 검색 필터링을 나무위키 차단과 같이 있게 할 수 있게 하면 좋겠습니다. (UX 검토중)
- [x] 그리고 나무위키 차단을 끄고 새로고침 할 때 다시 원래 들어갈려고 했던 화면이 나왔으면 좋겠습니다. (비활성화 후 링크 클릭으로 대체)

**Comment by Alex4386** [comment]
*기능 하나 당 이슈 하나씩 부탁드려요 ㅠㅠ*  

1. 0.7.0 구현 중입니다! 설정 화면을 따로 분리하고 있습니다.  
2. 검색필터링의 경우 현재 나무위키 설정 화면에 보시면 `검색 엔진 필터링`이라는 이름으로 존재합니다!  
3. UX 개선 적극 검토해 보겠습니다.

**Comment by Alex4386** [comment]
3번은 커밋 bdecba372ed32a3e867582d7b76fa96444ca279a 에서 수정되었습니다.

**Comment by Alex4386** [comment]
- [ ] 차단 안내 화면에 문구나 링크를 추가 할 수 있으면 좋겠습니다.
- [x] 검색 필터링을 나무위키 차단과 같이 있게 할 수 있게 하면 좋겠습니다. (이미 해당 형태로 설정됨)
- [x] 그리고 나무위키 차단을 끄고 새로고침 할 때 다시 원래 들어갈려고 했던 화면이 나왔으면 좋겠습니다. (비활성화 후 링크 클릭으로 대체)

**Comment by kweonsunho** [comment]
> 
> 
>     * [ ]  차단 안내 화면에 문구나 링크를 추가 할 수 있으면 좋겠습니다.
> 
>     * [x]  검색 필터링을 나무위키 차단과 같이 있게 할 수 있게 하면 좋겠습니다. (이미 해당 형태로 설정됨)
> 
>     * [x]  그리고 나무위키 차단을 끄고 새로고침 할 때 다시 원래 들어갈려고 했던 화면이 나왔으면 좋겠습니다. (비활성화 후 링크 클릭으로 대체)

어..그러면 아직 안된 첫번 째 사항은 고려해 보겠다는 것인가요?
그리고 저는 나무위키 차단을 키면 검색 필터링도 켜지고, 나무위키 차단을 끄면 검색 필터링도 꺼지는 설정을 만들어 주시면 좋겠다고 한 질문이었는데요...

**Comment by Alex4386** [comment]
-> 추가 확인 했습니다.
2번 사항의 경우 UX 검토후 진행 하도록 하겠습니다.   
3번의 경우 0.7.0 에서 비활성화 한 후 링크 클릭을 통해 접근 할 수 있도록 변경 되었습니다.  

1번은 추후 개발 예정입니다.

**Comment by Alex4386** [comment]
1번 항목 개발 완료, 0.7.1 에 추가됩니다.

**Comment by Alex4386** [comment]
링크 추가는 Mozilla Firefox 내부에서 유저가 스크립팅, 링크 추가 허용시 추가기능 심사에서 저촉 되므로 불가능합니다.

**Comment by kweonsunho** [comment]
> 링크 추가는 Mozilla Firefox 추가기능 심사시 사용자가 스크립트, 링크 추가를 통해 플러그인의 기능을 수정할 수 있는 경우 추가기능 심사에서 저촉 되므로 불가능합니다.

그러면 그냥 프로그램으로 배포해서 링크 가능 버전으로 따로 하면 안될까요?
거기 리드미에 프로그램으로 배포해서 사용하는법 있잖아요.

**Comment by kweonsunho** [comment]
> 링크 추가는 Mozilla Firefox 추가기능 심사시 사용자가 스크립트, 링크 추가를 통해 플러그인의 기능을 수정할 수 있는 경우 추가기능 심사에서 저촉 되므로 불가능합니다.

그리고 브라우저가 끝날 때 자동으로 나무위키 차단이 다시 켜지게 할 수는 없나요?

**Comment by park012241** [comment]
현재 한 이슈에 여러가지의 요구사항이 생겨 읽기 힙듭니다.
불편하시더라도 issue를 나누어 요청해 주세요.

**Comment by park012241** [comment]
> 
> 
> > 링크 추가는 Mozilla Firefox 추가기능 심사시 사용자가 스크립트, 링크 추가를 통해 플러그인의 기능을 수정할 수 있는 경우 추가기능 심사에서 저촉 되므로 불가능합니다.
> 
> 그러면 그냥 프로그램(zip)으로 배포해서 링크 가능 버전으로 따로 하면 안될까요?
> 거기 리드미에 프로그램(zip)으로 배포해서 사용하는법 있잖아요.
> 링크 기능이 꼭 필요한데...

사실 Bitwarden(비밀번호 관리자), uBlock origin과 같은 확장 프로그램에서는 브라우저 확장에서는 사용자 지정 규칙을 추가할 수 없고, 웹에서만 추가할 수 있습니다.
설정을 싱크하는 기능이 추가되지 않는 이상 어려울 것으로 보입니다.

쿠키와 같은 곳에 저장하더라도 Mozila또는 Google에서 코드를 읽으므로 어려울 수도 있을 것 같습니다.

**Comment by park012241** [comment]
Bitwarden에서는 단지 도메인간의 관계를 정의하는 데에만 사용자 규칙을 사용하고 있고,
uBlock origin에서는 "객체의 표시 차단"을 위해서 사용자 정의 규칙을 이용합니다.

원하시는 정확한 feature가 무엇인지 모르겠지만, "완전히 차단"할 사이트들을 정의하거나 차단 후 이동할 사이트를 정의하는 것은 어려워 보입니다.

**Comment by Alex4386** [comment]
> > 링크 추가는 Mozilla Firefox 추가기능 심사시 사용자가 스크립트, 링크 추가를 통해 플러그인의 기능을 수정할 수 있는 경우 추가기능 심사에서 저촉 되므로 불가능합니다.
> 
> 그러면 그냥 프로그램(zip)으로 배포해서 링크 가능 버전으로 따로 하면 안될까요?
> 거기 리드미에 프로그램(zip)으로 배포해서 사용하는법 있잖아요.
> 링크 기능이 꼭 필요한데...

아시다시피 이 레포지토리의 경우 확장 스토어에 올라와 있는 확장의 소스코드를 올려놓은 레포지토리입니다.

물론, 모든 이용자 분께서 직접 빌드하는 방법도 존재합니다. 

그러나 그 방법 (zip을 빌드해 브라우저에 추가하는 방법)은 *Sideload* 를 이용하는 방법으로, 각 브라우저 개발사에서 개발 목적으로만 허용하고 있는 방법입니다.
(특히 Firefox Browser의 경우, Sideload한 확장은 한번 재시작 하면 사라짐)

또한, 해당 피쳐가 반드시 필요하신 경우, 이 확장 프로그램은 오픈소스입니다.

우측 상단의 Fork 버튼을 누르면, 현재 레포지토리를 클론 하여 라이선스가 허용하는 구역 내에서 수정하여 이용하실 수 있습니다.

**Comment by kweonsunho** [comment]
> > > 링크 추가는 Mozilla Firefox 추가기능 심사시 사용자가 스크립트, 링크 추가를 통해 플러그인의 기능을 수정할 수 있는 경우 추가기능 심사에서 저촉 되므로 불가능합니다.
> > 
> > 
> > 그러면 그냥 프로그램(zip)으로 배포해서 링크 가능 버전으로 따로 하면 안될까요?
> > 거기 리드미에 프로그램(zip)으로 배포해서 사용하는법 있잖아요.
> > 링크 기능이 꼭 필요한데...
> 
> 아시다시피 이 레포지토리의 경우 확장 스토어에 올라와 있는 확장의 소스코드를 올려놓은 레포지토리입니다.
> 
> 물론, 모든 이용자 분께서 직접 빌드하는 방법도 존재합니다.
> 
> 그러나 그 방법 (zip을 빌드해 브라우저에 추가하는 방법)은 _Sideload_ 를 이용하는 방법으로, 각 브라우저 개발사에서 개발 목적으로만 허용하고 있는 방법입니다.
> (특히 Firefox Browser의 경우, Sideload한 확장은 한번 재시작 하면 사라짐)
> 
> 또한, 해당 피쳐가 반드시 필요하신 경우, 이 확장 프로그램은 오픈소스입니다.
> 
> 우측 상단의 Fork 버튼을 누르면, 현재 레포지토리를 클론 하여 라이선스가 허용하는 구역 내에서 수정하여 이용하실 수 있습니다.

그러면 글 추가 기능은 추가 되는거죠?

**Comment by Alex4386** [comment]
0.7.1에서 이미 추가 된 기능입니다.

**Comment by Alex4386** [comment]
> > 링크 추가는 Mozilla Firefox 추가기능 심사시 사용자가 스크립트, 링크 추가를 통해 플러그인의 기능을 수정할 수 있는 경우 추가기능 심사에서 저촉 되므로 불가능합니다.
> 
> 그리고 브라우저가 끝날 때 자동으로 나무위키 차단이 다시 켜지게 할 수는 없나요?

해당 사항에 경우 WebExtensions API 에 지원하는 API 가 없어 구현 할 수 없습니다.

https://stackoverflow.com/questions/3390470/event-onbrowserclose-for-google-chrome-extension

**Comment by kweonsunho** [comment]
> > > 링크 추가는 Mozilla Firefox 추가기능 심사시 사용자가 스크립트, 링크 추가를 통해 플러그인의 기능을 수정할 수 있는 경우 추가기능 심사에서 저촉 되므로 불가능합니다.
> > 
> > 
> > 그리고 브라우저가 끝날 때 자동으로 나무위키 차단이 다시 켜지게 할 수는 없나요?
> 
> 해당 사항의 경우 WebExtensions API 에 지원하는 API 가 없어 구현 할 수 없습니다.
> 
> 그러나 아래 기능을 background script에 포함해서 이용할 수 있을 것으로 생각됩니다.
> https://stackoverflow.com/questions/3390470/event-onbrowserclose-for-google-chrome-extension

그러면 구현을 도와 주세요

**Comment by Alex4386** [comment]
HTML 문법은 알고 계시죠? 웹페이지 렌더 쪽 자바 스크립트에서 HTML 문법을 escaping 하는 함수를 거치지 않도록 하시면 됩니다.

**Comment by Alex4386** [comment]
> > > 링크 추가는 Mozilla Firefox 추가기능 심사시 사용자가 스크립트, 링크 추가를 통해 플러그인의 기능을 수정할 수 있는 경우 추가기능 심사에서 저촉 되므로 불가능합니다.
> > 
> > 
> > 그리고 브라우저가 끝날 때 자동으로 나무위키 차단이 다시 켜지게 할 수는 없나요?
> 
> 해당 사항의 경우 WebExtensions API 에 지원하는 API 가 없어 구현 할 수 없습니다.
> 
> 그러나 아래 기능을 background script에 포함해서 이용할 수 있을 것으로 생각됩니다.
> https://stackoverflow.com/questions/3390470/event-onbrowserclose-for-google-chrome-extension

해당 경우, Background JavaScript의 코드를 변경하여 해당 부분에 브라우저를 닫는 부분을 추가해 주시면 됩니다.

**Comment by Alex4386** [comment]
추가적으로:
[CONTRIBUTORS.md](https://github.com/Alex4386/turnoff-namuwiki/blob/master/CONTRIBUTORS.md) 파일을 참고하시면 더욱 좋을 것 같네요.  

이슈 닫겠습니다.
