### ISSUE TITLE
한번에 키고 끌 수 있는 버튼

### ISSUE THREAD

**Issue by kweonsunho** [Alex4386/turnoff-namuwiki#27]
# ISSUE: Feature Request
## 추가를 원하는 기능이 무엇인가요? What kind of feature you are requesting?
- [ ] 논문 웹페이지 추가 지원 (more journal page support)  
- [ ] 나무위키 제거 검색엔진 추가 (more search result filters for Search Engine)  
- [ O] UX (사용자 경험) 개선 (User Experience Enhancements)
- [ ] 그 외 (Others)  

## 어떤 기능을 추가했으면 좋을까요? (What feature you are requesting?)
**정확하게 설명해 주세요** (Please explain it in detail)
상단바에서 버튼 하나로 나무위키 차단을 켜고 끌 수 있으면 좋겠습니다.

**Comment by Alex4386** [comment]
Invalid.  
WebExtensions 표준에 따라 상단에는 확장마다 최대 한개의 아이콘만 가능합니다.
