### ISSUE TITLE
[Feature Request] intelliBan 허용 범위 확대

### ISSUE THREAD

**Issue by kweonsunho** [Alex4386/turnoff-namuwiki#28]
# ISSUE: Feature Request
## 추가를 원하는 기능이 무엇인가요? What kind of feature you are requesting?
- [ ] 논문 웹페이지 추가 지원 (more journal page support)  
- [ ] 나무위키 제거 검색엔진 추가 (more search result filters for Search Engine)  
- [X] UX (사용자 경험) 개선 (User Experience Enhancements)
- [ ] 그 외 (Others)  

## 어떤 기능을 추가했으면 좋을까요? (What feature you are requesting?)
**정확하게 설명해 주세요** (Please explain it in detail)
인텔리밴 할 때 게임,음악,만화,영화 등도 허용해 주시고 그러면 나무위키 대문 정도는 뚫어놔야 될 것 같습니다.
~~그리고 나무위키 쳤을 때 나오는  논문 사이트에 원하는 사이트를 추가 할 수 있게 하거나 다른 위키들을 넣어놨으면 좋겠습니다. (새로운 이슈로 생성 바랍니다. 해당 경우 원하는 것을 개인으로 추가 할 수 있는 기능은 역시 script 직접 접근 이기에 추가 불가능 합니다.)~~

**Comment by Alex4386** [comment]
**제발 기능 추가 요청 하나 마다 하나씩 부탁드립니다**  
   
# IntelliBan 대문 적용의 경우
IntelliBan의 경우 이 GitHub Repository 에서 동기화 되기 때문에, 이 레포에 갱신 하는 경우 바로 모든 시스템 이용자에게 적용됩니다.  

해당 intelliBan 정보는 [intelliBan/rules.json](https://github.com/Alex4386/turnoff-namuwiki/blob/master/intelliBan/rules.json) 에서 추가 요청 하실 수 있습니다.  
  
그러나, Wikipedia에 자세한 정보가 명시 되지 않아 나무위키가 최상위의 정보만을 제공하는 경우를 제외 하고는 게임, 음악, 만화, 영화의 추가는 어렵습니다.  
ex. 추가 불가 예제: [Team Fortress 2](https://ko.wikipedia.org/wiki/%ED%8C%80_%ED%8F%AC%ED%8A%B8%EB%A6%AC%EC%8A%A4_2)  
  
해당 경우 turnoff-namuwiki의 목적은 나무위키에 대한 접속을 차단, 인터넷 상의 더욱 신뢰성 있는 데이터로의 접근을 유도하여야 합니다. 해당 목적은 제가 maintaining하는 turnoff-namuwiki의 궁극적인 목표이며, 해당 목적에 부합하신다면 본인의 포크판을 만들어서 사용하시는 것을 권장합니다.  

해당 기능이 필요한 경우, 룰셋을 gist 등에 업로드 하여서 커스텀 룰셋으로 배포하시면 됩니다.  
  
단, 2차 창작, 동인 게임 등의 정확한 정보의 근원지 추적 및 데이터의 신뢰성을 커뮤니티가 만들어 가는 경우, 나무위키 접속을 허용할 예정입니다. ex. [동방 프로젝트](https://namu.wiki/w/%EB%8F%99%EB%B0%A9%20%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8)

**Comment by kweonsunho** [comment]
> 해당 경우 turnoff-namuwiki의 목적은 나무위키에 대한 접속을 차단, 인터넷 상의 더욱 신뢰성 있는 데이터로의 접근을 유도하여야 합니다. 해당 목적은 제가 maintaining하는 turnoff-namuwiki의 궁극적인 목표이며, 해당 목적에 부합하신다면 본인의 포크판을 만들어서 사용하시는 것을 권장합니다.


그러면 나무위키 대문을 뚫는 것은 어떻게 생각하시나요?
그리고 논문 사이트에 다른 사이트를 추가 할 수 있게 하는 건요?

**Comment by Alex4386** [comment]
최상단에 제가 수정한 사항 확인해 주시면 됩니다. 유저가 탭 리다이렉션을 지정할 수 있는 부분에서 심사 저촉 가능성이 있습니다.

**Comment by Alex4386** [comment]
**이슈 하나당 기능 요청 하나씩 부탁드립니다. 제발요.**

최상단에 제가 수정한 사항 확인해 주시면 됩니다. 유저가 탭 리다이렉션을 지정할 수 있는 부분에서 심사 저촉 가능성이 있습니다. 
그렇기 때문에 논문사이트 추가의 경우 원하는 웹페이지를 따로 이슈로 넣어달라고 요청 드리는 겁니다.

나무위키:대문은 앞에서 알려 드린대로 이미 적용 됐습니다.

**Comment by Alex4386** [comment]
저번에 말씀 드린대로 심사에 저촉되어 내려야 하는 경우에는 기능 추가를 하지 않을 생각입니다. 
CONTRIBUTORS.md 문서에서 신규 신설되었습니다.

이유는 다음과 같습니다.
1. 사용자의 접근성 위해
2. 이미 turnoff-namuwiki 를 확장 스토어를 통해 이용 중인 사용자에 대해 지원 중단을 해야 함.

현재 구글 크롬 확장 스토어 기준 43명이 사용하는 상황이기에, 함부로 지원을 중단하기는 어렵습니다.
