### ISSUE TITLE
[Feature Request] 리다이렉션 대상으로의 위키백과 또는 리브레위키 추가

### ISSUE THREAD

**Issue by kweonsunho** [Alex4386/turnoff-namuwiki#29]
# ISSUE: Feature Request
## 추가를 원하는 기능이 무엇인가요? What kind of feature you are requesting?
- [x] 논문 웹페이지 추가 지원 (more journal page support)  
- [ ] 나무위키 제거 검색엔진 추가 (more search result filters for Search Engine)  
- [ ] UX (사용자 경험) 개선 (User Experience Enhancements)
- [ ] 그 외 (Others)  

## 어떤 기능을 추가했으면 좋을까요? (What feature you are requesting?)
**정확하게 설명해 주세요** (Please explain it in detail)
추가 원하는 사이트 목록입니다.
리브레 위키, 위키백과

**Comment by Alex4386** [comment]
Firefox 정책 보고 기능 v.0.8.0 에서의 추가 여부 검토하겠습니다.

**Comment by Alex4386** [comment]
@kweonsunho 
마크다운 문법에서 체크 박스 문법은

```
* [V]
```
가 아닌

```
* [X]
```
입니다. 추후 이슈 생성시 적용 부탁드립니다.

**Comment by Alex4386** [comment]
해당 사항(리브레위키 차단, 위키백과 차단)은 Breaking Changes로 분류되며, 아마도 해당 사항의 경우 현재 이름에 적합하지 않아 새로운 프로젝트에 적합 할 것 같습니다.

**Comment by kweonsunho** [comment]
그게 아니라 나무위키가 차단됬을 때 다른 위키 사이트로 연결되게 하달라는 거인데요...

**Comment by kweonsunho** [comment]
> 해당 사항(리브레위키 차단, 위키백과 차단)은 Breaking Changes로 분류되며, 아마도 해당 사항의 경우 현재 이름에 적합하지 않아 새로운 프로젝트에 적합 할 것 같습니다.

그리고 
 위키 사이트에 문서가 있을 때만 그 위키의 문서를 띄워 주고 아니면 나무위키의 문서를 풀어줘 보여주는 기능이 있으면 좋겠습니다. 그리고 문서가 없을 시에는 문서 만들기 링크로 가게 할지 아니면 아예 보여주지 말지도 버튼 등으로 정할 수 있으면 좋겠습니다.그리고 문서 글자수에 따라 나무위키로 갈 지 아니면 다른 위키로 갈 지도 정할 수 있게 하면 좋겠습니다.
이 내용도 거기와 연결되는 것으로... 다른 위키로 넘겨졌을 때 문서 내용이 없을 시 문서 만들기 페이지로 연결되면 좋겠고요, 문서 글자 수를 세서 몇자 이상이면 나무위키 문서를 뚫고 다른 위키 사이트의 문서 만들기 페이지로 연결될지 말지는 버튼으로 정하게 하고...  아니면 나무위키를 차단하고  다른 위키 사이트를 보여주고... 이렇게 하면 좋겠다는 것이었는데요...

**Comment by kweonsunho** [comment]
> 해당 사항(리브레위키 차단, 위키백과 차단)은 Breaking Changes로 분류되며, 아마도 해당 사항의 경우 현재 이름에 적합하지 않아 새로운 프로젝트에 적합 할 것 같습니다.

그게 아니라 나무위키가 차단됬을 때 다른 위키 사이트로 연결되게 하달라는 거인데요...

**Comment by Alex4386** [comment]
리다이렉션 대상으로의 리브레위키는 역시나 공신력을 보장할 수 없기에 사용자의 니즈가 많은 경우에만 적용하도록 하겠습니다.  
  
위키백과는 공신력에 대해서는 부족하나 견제를 위한 *[citation needed]* 가 있기에 추가를 고려 해 보고 말씀 드리겠습니다.

**Comment by kweonsunho** [comment]
> 리다이렉션 대상으로의 리브레위키는 역시나 공신력을 보장할 수 없기에 사용자의 니즈가 많은 경우에만 적용하도록 하겠습니다.
> 
> 위키백과는 공신력에 대해서는 부족하나 견제를 위한 _[citation needed]_ 가 있기에 추가를 고려 해 보고 말씀 드리겠습니다.

혹시 리다이렉션 코드를 좀 설명해 주실 수 있나요? 제가 포크해 보겠습니다.

**Comment by Alex4386** [comment]
리다이렉션은 bg.ts 쪽에 존재합니다.

**Comment by Alex4386** [comment]
[bg.ts 74번 줄](https://github.com/Alex4386/turnoff-namuwiki/blob/master/src/bg.ts#L94) 부터 확인 하시면 됩니다.

**Comment by kweonsunho** [comment]
> [bg.ts 74번 줄](https://github.com/Alex4386/turnoff-namuwiki/blob/master/src/bg.ts#L94) 부터 확인 하시면 됩니다.

띄어쓰기는 어떻게 처리하나요? 리브레 위키는 )_(밑줄)로 띄어쓰기를 합니다.

**Comment by Alex4386** [comment]
> > [bg.ts 74번 줄](https://github.com/Alex4386/turnoff-namuwiki/blob/master/src/bg.ts#L94) 부터 확인 하시면 됩니다.
> 
> 띄어쓰기는 어떻게 처리하나요? 리브레 위키는 )_(밑줄)로 띄어쓰기를 합니다.

![image](https://user-images.githubusercontent.com/27724108/82190709-69271080-992c-11ea-87c1-10512c0cf016.png)
searchQuery의 경우 상단에서 decodeURIComponent를 실행 하므로, _로 한다면, JavaScript의 string replace method를 통해 처리하면 되겠습니다. (TypeScript는 JavaScript의 superset이므로)

**Comment by Alex4386** [comment]
해당 내용의 경우 직접적으로 Issue에 관련이 없으므로, JavaScript 가이드 문서를 참고하여서 개발하여 주시면 감사하겠습니다.

**Comment by kweonsunho** [comment]
> > > [bg.ts 74번 줄](https://github.com/Alex4386/turnoff-namuwiki/blob/master/src/bg.ts#L94) 부터 확인 하시면 됩니다.
> > 
> > 
> > 띄어쓰기는 어떻게 처리하나요? 리브레 위키는 )_(밑줄)로 띄어쓰기를 합니다.
> 
> ![image](https://user-images.githubusercontent.com/27724108/82190709-69271080-992c-11ea-87c1-10512c0cf016.png)
> searchQuery의 경우 상단에서 decodeURIComponent를 실행 하므로, _로 한다면, JavaScript의 string replace method를 통해 처리하면 되겠습니다. (TypeScript는 JavaScript의 superset이므로)

코드를 만들어 주시면 안 될까요? 불편하셨다면 죄송합니다.

**Comment by kweonsunho** [comment]
> 해당 내용의 경우 직접적으로 Issue에 관련이 없으므로, JavaScript 가이드 문서를 참고하여서 개발하여 주시면 감사하겠습니다.

알겠습니다. 죄송합니다.

**Comment by kweonsunho** [comment]
> 해당 내용의 경우 직접적으로 Issue에 관련이 없으므로, JavaScript 가이드 문서를 참고하여서 개발하여 주시면 감사하겠습니다.

그리고 매뉴 버튼은 어떻게 make하나요?

**Comment by kweonsunho** [comment]
> > 해당 내용의 경우 직접적으로 Issue에 관련이 없으므로, JavaScript 가이드 문서를 참고하여서 개발하여 주시면 감사하겠습니다.
> 
> 그리고 매뉴 버튼은 어떻게 make하나요?

아니면 매뉴가 허용이 되지 않아도 그냥 적용 시키는 방법은 없나요?
if 문 없이 하면 되나요?

**Comment by Alex4386** [comment]
네

**Comment by kweonsunho** [comment]
> 네
그러니까 이런 if문 없이 그냥 
if (config.openGoogleScholar && langCode) {
              if (searchQuery && !/^나무위키:.+/.test(searchQuery)) {
요 if문에다 작성하면 되는 것이죠!

**Comment by Alex4386** [comment]
> > 해당 내용의 경우 직접적으로 Issue에 관련이 없으므로, JavaScript 가이드 문서를 참고하여서 개발하여 주시면 감사하겠습니다.
> 
> 그리고 매뉴 버튼은 어떻게 make하나요?

메뉴 버튼은 [https://github.com/Alex4386/turnoff-namuwiki/tree/master/interface](https://github.com/Alex4386/turnoff-namuwiki/tree/master/interface)
그리고 설정페이지 쪽의 경우 [https://github.com/Alex4386/turnoff-namuwiki/blob/master/src/settings.ts](https://github.com/Alex4386/turnoff-namuwiki/blob/master/src/settings.ts), 그리고 팝업메뉴의 경우 [https://github.com/Alex4386/turnoff-namuwiki/blob/master/src/popup.ts](https://github.com/Alex4386/turnoff-namuwiki/blob/master/src/popup.ts) 를 수정하시면 됩니다.

**Comment by Alex4386** [comment]
> > 네
> > 그러니까 이런 if문 없이 그냥
> > if (config.openGoogleScholar && langCode) {
> > if (searchQuery && !/^나무위키:.+/.test(searchQuery)) {
> > 요 if문에다 작성하면 되는 것이죠!

네.

**Comment by kweonsunho** [comment]
> > > 해당 내용의 경우 직접적으로 Issue에 관련이 없으므로, JavaScript 가이드 문서를 참고하여서 개발하여 주시면 감사하겠습니다.
> > 
> > 
> > 그리고 매뉴 버튼은 어떻게 make하나요?
> 
> 메뉴 버튼은 https://github.com/Alex4386/turnoff-namuwiki/tree/master/interface
> 그리고 설정페이지 쪽의 경우 https://github.com/Alex4386/turnoff-namuwiki/blob/master/src/settings.ts, 그리고 팝업메뉴의 경우 https://github.com/Alex4386/turnoff-namuwiki/blob/master/src/popup.ts 를 수정하시면 됩니다.

그런데 파이어폭스에서는 띄어쓰기를 한 링크를 주소창에 넣어도 잘 반응하는데, 그냥 놔둬도 되는 건가요?

**Comment by Alex4386** [comment]
> > > > 해당 내용의 경우 직접적으로 Issue에 관련이 없으므로, JavaScript 가이드 문서를 참고하여서 개발하여 주시면 감사하겠습니다.
> > > 
> > > 
> > > 그리고 매뉴 버튼은 어떻게 make하나요?
> > 
> > 
> > 메뉴 버튼은 https://github.com/Alex4386/turnoff-namuwiki/tree/master/interface
> > 그리고 설정페이지 쪽의 경우 https://github.com/Alex4386/turnoff-namuwiki/blob/master/src/settings.ts, 그리고 팝업메뉴의 경우 https://github.com/Alex4386/turnoff-namuwiki/blob/master/src/popup.ts 를 수정하시면 됩니다.
> 
> 그런데 파이어폭스에서는 띄어쓰기를 한 링크를 주소창에 넣어도 잘 반응하는데, 그냥 놔둬도 되는 건가요?

이해 할 수 없습니다.

**Comment by kweonsunho** [comment]
> > > > > 해당 내용의 경우 직접적으로 Issue에 관련이 없으므로, JavaScript 가이드 문서를 참고하여서 개발하여 주시면 감사하겠습니다.
> > > > 
> > > > 
> > > > 그리고 매뉴 버튼은 어떻게 make하나요?
> > > 
> > > 
> > > 메뉴 버튼은 https://github.com/Alex4386/turnoff-namuwiki/tree/master/interface
> > > 그리고 설정페이지 쪽의 경우 https://github.com/Alex4386/turnoff-namuwiki/blob/master/src/settings.ts, 그리고 팝업메뉴의 경우 https://github.com/Alex4386/turnoff-namuwiki/blob/master/src/popup.ts 를 수정하시면 됩니다.
> > 
> > 
> > 그런데 파이어폭스에서는 띄어쓰기를 한 링크를 주소창에 넣어도 잘 반응하는데, 그냥 놔둬도 되는 건가요?
> 
> 이해 할 수 없습니다.

그러니까  파이어폭스에서는 주소창에 namu.wiki/w/고 기
이렇게 쳐도 고 기 문서로 잘 이동된다는 소립니다.

**Comment by Alex4386** [comment]
intelliBan 이 켜져있다면 나무위키:대문은 접속이 가능합니다.

**Comment by Alex4386** [comment]
저번이 @kweonsunho 님이 직접 여셨던 #28 에서 적용된 사항입니다.

**Comment by kweonsunho** [comment]
> intelliBan 이 켜져있다면 나무위키:대문은 접속이 가능합니다.

저... 그게 예시로 든 것이고요... 넘겨주기 할 때 파이어폭스는 자동으로 띄어쓰기 생성해 주는데 그러면 
https://github.com/Alex4386/turnoff-namuwiki/issues/29#issuecomment-630029293
요 내용대로 하지 않아도 되나요?

**Comment by Alex4386** [comment]
> > > > [bg.ts 74번 줄](https://github.com/Alex4386/turnoff-namuwiki/blob/master/src/bg.ts#L94) 부터 확인 하시면 됩니다.
> > > 
> > > 
> > > 띄어쓰기는 어떻게 처리하나요? 리브레 위키는 )_(밑줄)로 띄어쓰기를 합니다.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/27724108/82190709-69271080-992c-11ea-87c1-10512c0cf016.png)
> > searchQuery의 경우 상단에서 decodeURIComponent를 실행 하므로, _로 한다면, JavaScript의 string replace method를 통해 처리하면 되겠습니다. (TypeScript는 JavaScript의 superset이므로)
> 
> 코드를 만들어 주시면 안 될까요? 불편하셨다면 죄송합니다.

해당 익스텐션에 대한 지원이 아니므로 지원이 어렵습니다.

**Comment by kweonsunho** [comment]
> 주시면

네... 그러면 제가 알아서 처리할게요...

**Comment by Alex4386** [comment]
> > > > > > 해당 내용의 경우 직접적으로 Issue에 관련이 없으므로, JavaScript 가이드 문서를 참고하여서 개발하여 주시면 감사하겠습니다.
> > > > > 
> > > > > 
> > > > > 그리고 매뉴 버튼은 어떻게 make하나요?
> > > > 
> > > > 
> > > > 메뉴 버튼은 https://github.com/Alex4386/turnoff-namuwiki/tree/master/interface
> > > > 그리고 설정페이지 쪽의 경우 https://github.com/Alex4386/turnoff-namuwiki/blob/master/src/settings.ts, 그리고 팝업메뉴의 경우 https://github.com/Alex4386/turnoff-namuwiki/blob/master/src/popup.ts 를 수정하시면 됩니다.
> > > 
> > > 
> > > 그런데 파이어폭스에서는 띄어쓰기를 한 링크를 주소창에 넣어도 잘 반응하는데, 그냥 놔둬도 되는 건가요?
> > 
> > 
> > 이해 할 수 없습니다.
> 
> 그러니까 파이어폭스에서는 주소창에 namu.wiki/w/고 기
> 이렇게 쳐도 고 기 문서로 잘 이동된다는 소립니다.
> _로 하는 리브레 위키도 잘 되네요.

현재 master 코드에서 재 구현 실패인 것으로 보아 수정하신 코드에 문제가 있는 것 같습니다.  
제 코드의 버그가 아니므로 지원 드릴 수 없습니다.

**Comment by Alex4386** [comment]
@kweonsunho 구현에 어려움을 겪는 것 같아 제 레포지토리에서 위키백과 및 리브레위키 추가를 추가한 브랜치를 추가 신설하겠습니다.

**Comment by Alex4386** [comment]
@kweonsunho [feature/add-librewiki-and-wikipedia](https://github.com/Alex4386/turnoff-namuwiki/tree/feature/add-librewiki-and-wikipedia) 브랜치에 기능을 추가 했습니다.  

추후 사용자 필요성 검토후 master에 머지 하겠습니다.

**Comment by Alex4386** [comment]
-> 이러한 사항에 대해서는: 논문 웹페이지 추가 지원에 해당합니다.  
     추후 빠른 이해를 위해 정확한 카테고리 분류 부탁드립니다.

**Comment by Alex4386** [comment]
내부 심사를 완료 했습니다.  
Turnoff-namuwiki는 **조별과제에서 부정확한 정보를 가져오는 사람들을 위한 정확한 정보로의 유도**로, **리브레위키, 위키백과와 같이 정보의 정확성을 완벽하게 보증 할 수 없는 경우에는 추가가 불가능 하다고 판단 했습니다.**

단, 위키백과의 경우 정보 정확성이 공신력 없는 자료의 경우 자정작용이 일어나는 것을 바탕으로 Disclaimer를 걸고 추가하기로 하였으나, **리브레위키의 경우 공신력이 없는 자료를 근거로 가져왔을 때 citation needed 와 같은 견제 시스템이 없는 관계로 리다이렉션 대상으로 정하기 어렵다는 판단을 내렸습니다.**  
  
따라서 위키백과의 경우 *커뮤니티 자동접속* 부분으로 추가할 계획이나, *리브레위키*로의 자동 접속의 경우 처리가 다소 어렵습니다.  

이것이 공감하기에 어려우시다면, 조별과제에 위키백과 pdf본은 상대적으로 정보를 가공 할 수 있겠으나,  
리브레위키 pdf본의 경우 처음 부터 신뢰도가 떨어져 발표 자료로 이용하기 어려운 것으로 생각해 보시면 될 것 같습니다.  

Issue 닫겠습니다.

**Comment by Alex4386** [comment]
> 내부 심사를 완료 했습니다.
> Turnoff-namuwiki는 **조별과제에서 부정확한 정보를 가져오는 사람들을 위한 정확한 정보로의 유도**로, **리브레위키, 위키백과와 같이 정보의 정확성을 완벽하게 보증 할 수 없는 경우에는 추가가 불가능 하다고 판단 했습니다.**
> 
> 단, 위키백과의 경우 정보 정확성이 공신력 없는 자료의 경우 자정작용이 일어나는 것을 바탕으로 Disclaimer를 걸고 추가하기로 하였으나, **리브레위키의 경우 공신력이 없는 자료를 근거로 가져왔을 때 citation needed 와 같은 견제 시스템이 없는 관계로 리다이렉션 대상으로 정하기 어렵다는 판단을 내렸습니다.**
> 
> 따라서 위키백과의 경우 _커뮤니티 자동접속_ 부분으로 추가할 계획이나, _리브레위키_로의 자동 접속의 경우 처리가 다소 어렵습니다.
> 
> 이것이 공감하기에 어려우시다면, 조별과제에 위키백과 pdf본은 상대적으로 정보를 가공 할 수 있겠으나,
> 리브레위키 pdf본의 경우 처음 부터 신뢰도가 떨어져 발표 자료로 이용하기 어려운 것으로 생각해 보시면 될 것 같습니다.
> 
> Issue 닫겠습니다.

단 기능 자체는 구현이 되어있으므로, [https://github.com/Alex4386/turnoff-namuwiki/tree/feature/add-librewiki-and-wikipedia] 에 있는 코드를 다운로드 해서 쓰시면 됩니다.

**Comment by kweonsunho** [comment]
> > 내부 심사를 완료 했습니다.
> > Turnoff-namuwiki는 **조별과제에서 부정확한 정보를 가져오는 사람들을 위한 정확한 정보로의 유도**로, **리브레위키, 위키백과와 같이 정보의 정확성을 완벽하게 보증 할 수 없는 경우에는 추가가 불가능 하다고 판단 했습니다.**
> > 단, 위키백과의 경우 정보 정확성이 공신력 없는 자료의 경우 자정작용이 일어나는 것을 바탕으로 Disclaimer를 걸고 추가하기로 하였으나, **리브레위키의 경우 공신력이 없는 자료를 근거로 가져왔을 때 citation needed 와 같은 견제 시스템이 없는 관계로 리다이렉션 대상으로 정하기 어렵다는 판단을 내렸습니다.**
> > 따라서 위키백과의 경우 _커뮤니티 자동접속_ 부분으로 추가할 계획이나, _리브레위키_로의 자동 접속의 경우 처리가 다소 어렵습니다.
> > 이것이 공감하기에 어려우시다면, 조별과제에 위키백과 pdf본은 상대적으로 정보를 가공 할 수 있겠으나,
> > 리브레위키 pdf본의 경우 처음 부터 신뢰도가 떨어져 발표 자료로 이용하기 어려운 것으로 생각해 보시면 될 것 같습니다.
> > Issue 닫겠습니다.
> 
> 단 기능 자체는 구현이 되어있으므로, [feature/add-librewiki-and-wikipedia](https://github.com/Alex4386/turnoff-namuwiki/tree/feature/add-librewiki-and-wikipedia) 에 있는 코드를 다운로드 해서 쓰시면 됩니다.

감사합니다.! 제가 수정한 코드가 성공했습니다!

**Comment by kweonsunho** [comment]
> > 내부 심사를 완료 했습니다.
> > Turnoff-namuwiki는 **조별과제에서 부정확한 정보를 가져오는 사람들을 위한 정확한 정보로의 유도**로, **리브레위키, 위키백과와 같이 정보의 정확성을 완벽하게 보증 할 수 없는 경우에는 추가가 불가능 하다고 판단 했습니다.**
> > 단, 위키백과의 경우 정보 정확성이 공신력 없는 자료의 경우 자정작용이 일어나는 것을 바탕으로 Disclaimer를 걸고 추가하기로 하였으나, **리브레위키의 경우 공신력이 없는 자료를 근거로 가져왔을 때 citation needed 와 같은 견제 시스템이 없는 관계로 리다이렉션 대상으로 정하기 어렵다는 판단을 내렸습니다.**
> > 따라서 위키백과의 경우 _커뮤니티 자동접속_ 부분으로 추가할 계획이나, _리브레위키_로의 자동 접속의 경우 처리가 다소 어렵습니다.
> > 이것이 공감하기에 어려우시다면, 조별과제에 위키백과 pdf본은 상대적으로 정보를 가공 할 수 있겠으나,
> > 리브레위키 pdf본의 경우 처음 부터 신뢰도가 떨어져 발표 자료로 이용하기 어려운 것으로 생각해 보시면 될 것 같습니다.
> > Issue 닫겠습니다.
> 
> 단 기능 자체는 구현이 되어있으므로, [feature/add-librewiki-and-wikipedia](https://github.com/Alex4386/turnoff-namuwiki/tree/feature/add-librewiki-and-wikipedia) 에 있는 코드를 다운로드 해서 쓰시면 됩니다.

님이 만들어 주신 것도 제가 해보겠습니다!

**Comment by kweonsunho** [comment]
> > > 내부 심사를 완료 했습니다.
> > > Turnoff-namuwiki는 **조별과제에서 부정확한 정보를 가져오는 사람들을 위한 정확한 정보로의 유도**로, **리브레위키, 위키백과와 같이 정보의 정확성을 완벽하게 보증 할 수 없는 경우에는 추가가 불가능 하다고 판단 했습니다.**
> > > 단, 위키백과의 경우 정보 정확성이 공신력 없는 자료의 경우 자정작용이 일어나는 것을 바탕으로 Disclaimer를 걸고 추가하기로 하였으나, **리브레위키의 경우 공신력이 없는 자료를 근거로 가져왔을 때 citation needed 와 같은 견제 시스템이 없는 관계로 리다이렉션 대상으로 정하기 어렵다는 판단을 내렸습니다.**
> > > 따라서 위키백과의 경우 _커뮤니티 자동접속_ 부분으로 추가할 계획이나, _리브레위키_로의 자동 접속의 경우 처리가 다소 어렵습니다.
> > > 이것이 공감하기에 어려우시다면, 조별과제에 위키백과 pdf본은 상대적으로 정보를 가공 할 수 있겠으나,
> > > 리브레위키 pdf본의 경우 처음 부터 신뢰도가 떨어져 발표 자료로 이용하기 어려운 것으로 생각해 보시면 될 것 같습니다.
> > > Issue 닫겠습니다.
> > 
> > 
> > 단 기능 자체는 구현이 되어있으므로, [feature/add-librewiki-and-wikipedia](https://github.com/Alex4386/turnoff-namuwiki/tree/feature/add-librewiki-and-wikipedia) 에 있는 코드를 다운로드 해서 쓰시면 됩니다.
> 
> 님이 만들어 주신 것도 제가 해보겠습니다!

오! 잘 됩니다! 이것도 스토어에 등록해 주세요!

**Comment by kweonsunho** [comment]
좀 어려우실 수도 있지만 문서의 내용이 없다면 안 보여주기 같은 기능도 도와주세요!

**Comment by kweonsunho** [comment]
그리고 문서의 목차 링크를 눌러도 위키가 나오는 문제가 있습니다.

**Comment by kweonsunho** [comment]
그리고 자꾸 새 탭이 나와 불편한데 현재 탭이 있을 경우에는 거기로 이동되게 하면 좋겠습니다.

**Comment by Alex4386** [comment]
> > > > 내부 심사를 완료 했습니다.
> > > > Turnoff-namuwiki는 **조별과제에서 부정확한 정보를 가져오는 사람들을 위한 정확한 정보로의 유도**로, **리브레위키, 위키백과와 같이 정보의 정확성을 완벽하게 보증 할 수 없는 경우에는 추가가 불가능 하다고 판단 했습니다.**
> > > > 단, 위키백과의 경우 정보 정확성이 공신력 없는 자료의 경우 자정작용이 일어나는 것을 바탕으로 Disclaimer를 걸고 추가하기로 하였으나, **리브레위키의 경우 공신력이 없는 자료를 근거로 가져왔을 때 citation needed 와 같은 견제 시스템이 없는 관계로 리다이렉션 대상으로 정하기 어렵다는 판단을 내렸습니다.**
> > > > 따라서 위키백과의 경우 _커뮤니티 자동접속_ 부분으로 추가할 계획이나, _리브레위키_로의 자동 접속의 경우 처리가 다소 어렵습니다.
> > > > 이것이 공감하기에 어려우시다면, 조별과제에 위키백과 pdf본은 상대적으로 정보를 가공 할 수 있겠으나,
> > > > 리브레위키 pdf본의 경우 처음 부터 신뢰도가 떨어져 발표 자료로 이용하기 어려운 것으로 생각해 보시면 될 것 같습니다.
> > > > Issue 닫겠습니다.
> > > 
> > > 
> > > 단 기능 자체는 구현이 되어있으므로, [feature/add-librewiki-and-wikipedia](https://github.com/Alex4386/turnoff-namuwiki/tree/feature/add-librewiki-and-wikipedia) 에 있는 코드를 다운로드 해서 쓰시면 됩니다.
> > 
> > 
> > 님이 만들어 주신 것도 제가 해보겠습니다!
> 
> 오! 잘 됩니다! 이것도 스토어에 등록해 주세요!

제가 보낸 메세지를 잘못 이해 하신거 같아. 다시 요약해 드리겠습니다.
https://github.com/Alex4386/turnoff-namuwiki/issues/29#issuecomment-630152324

1. 리브레위키는 정확도가 상대적으로 떨어져 (조별과제 조사용으로 사용하기 애매함) 리다이렉션으로 적용하기 힘듦.
2. 위키백과의 경우 정확도 보장은 되지 않으나 견제 시스템 자체는 존재하기에, 커뮤니티 리다이렉션으로 등록하겠음.

따라서 **리브레위키 자동접속은 적용이 되지 않을 예정. 위키백과만 적용 될 예정.**  
다음 버전에 적용될 예정이므로 추후 확인 바람.

**Comment by Alex4386** [comment]
> 좀 어려우실 수도 있지만 문서의 내용이 없다면 안 보여주기 같은 기능도 도와주세요!

이슈는 **제발** 기능 요청 하나 당 하나씩 부탁드립니다.

**Comment by Alex4386** [comment]
> 좀 어려우실 수도 있지만 문서의 내용이 없다면 안 보여주기 같은 기능도 도와주세요!

#32 와 같은 기술적 애로사항이 존재합니다.

**Comment by Alex4386** [comment]
> 그리고 문서의 목차 링크를 눌러도 위키가 나오는 문제가 있습니다.

증상 신고의 내용이 정확히 확인 할 수 없습니다.

**Comment by Alex4386** [comment]
# 이 이슈를 잠급니다.

## 사유
이 이슈의 핵심 내용인 `리다이렉션 대상으로의 위키백과 또는 리브레위키 추가` 가 이미 해결 되었음에도 다른 내용으로 이슈의 내용이 추가되고 있음.

**Comment by Alex4386** [comment]
# 업데이트
**추후 off-topic 질문이나 개발 질문이 있으신 경우, [GitHub Discussions](https://github.com/Alex4386/turnoff-namuwiki/discussions) 를 이용해 주세요!**
