### ISSUE TITLE
[Feature Request]만약 위키 사이트가 추가된다면

### ISSUE THREAD

**Issue by kweonsunho** [Alex4386/turnoff-namuwiki#30]
# ISSUE: Feature Request
## 추가를 원하는 기능이 무엇인가요? What kind of feature you are requesting?
- [ ] 논문 웹페이지 추가 지원 (more journal page support)  
- [ ] 나무위키 제거 검색엔진 추가 (more search result filters for Search Engine)  
- [V] UX (사용자 경험) 개선 (User Experience Enhancements)
- [ ] 그 외 (Others)  

## 어떤 기능을 추가했으면 좋을까요? (What feature you are requesting?)
**정확하게 설명해 주세요** (Please explain it in detail)
 위키 사이트에 문서가 있을 때만 그 위키의 문서를 띄워 주고 아니면 나무위키의 문서를 풀어줘 보여주는 기능이 있으면 좋겠습니다. 그리고 문서가 없을 시에는 문서 만들기 링크로 가게 할지 아니면 아예 보여주지 말지도 버튼 등으로 정할 수 있으면 좋겠습니다.그리고 문서 글자수에 따라 나무위키로 갈 지 아니면 다른 위키로 갈 지도 정할 수 있게 하면 좋겠습니다.

**Comment by Alex4386** [comment]
Turnoff-namuwiki 의 목적은 나무위키보다 더욱 정확한 콘텐츠로의 이동이지 나무위키의 저작물 퀄리티 향상을 목적으로 하는 프로젝트가 아닙니다.
