### ISSUE TITLE
[Bug]인텔리밴은 문서 제목만 보나요?

### ISSUE THREAD

**Issue by kweonsunho** [Alex4386/turnoff-namuwiki#31]
## 환경 (Tell me the environments when the bug occurs)
* [ ] Google Chrome (or Chromium)  
* [X] Mozilla Firefox
* [ ] Mozilla Firefox for Android

### 가능하다면 버전을 적어주세요 (What is your browser's version)
*(ex. Mozilla Firefox Developer Edition 69.0b4 64-bit)*
0.7.1

## 버그에 대해 설명해 주세요 (Describe the bug)
제가 그래서 인텔리밴 리스트를 만들었는데
[
  {
    "regex": "서브컬(처|쳐)",
    "flag": "g"
  }, {
    "regex": "오타쿠",
    "flag": "g"
  }, {
    "regex": "^나무위키:대문$",
    "flag": "g"
  }, {
    "regex": "^게임$",
    "flag": "g"
  }, {
    "regex": "^음악$",
    "flag": "g"
  }
]
이렇게 만들었습니다. 그런데 베토벤이란 문서에 들어갔는데(거기에는 음악이란 내용이 있습니다.) 차단이 풀어지지 않습니디. 혹시 인텔리밴은 문서 제목만 보나요? 그러면 문서 내용도 보게 바꿔 주셨스면 감사하겠습니다.

**Comment by Alex4386** [comment]
네, 문서명만 보고 작동합니다.

해당 내용은 정규식으로, 직접 작성해 주셔야 합니다.
