### ISSUE TITLE
[Feature Request]다시 써 봅니다.

### ISSUE THREAD

**Issue by kweonsunho** [Alex4386/turnoff-namuwiki#33]
# ISSUE: Feature Request
## 추가를 원하는 기능이 무엇인가요? What kind of feature you are requesting?
- [ ] 논문 웹페이지 추가 지원 (more journal page support)  
- [ ] 나무위키 제거 검색엔진 추가 (more search result filters for Search Engine)  
- [ ㅆ] UX (사용자 경험) 개선 (User Experience Enhancements)
- [ ] 그 외 (Others)  

## 어떤 기능을 추가했으면 좋을까요? (What feature you are requesting?)
**정확하게 설명해 주세요** (Please explain it in detail)
현재 인텔리밴에서는 문서의 제목만 보고 뚫어야 할 지 판정하잖아요? 그것을 문서의 내용에 인텔리밴 허용 목록의 단어가 있어도 뚫리게 해 주시면 감사하겠습니다.

**Comment by Alex4386** [comment]
Duplicate of #32. closing issue.

Opening issue #32.
