### ISSUE TITLE
[Development Flow] Agile Development를 고려한 이슈 생성 가이드라인 작성

### ISSUE THREAD

**Issue by Alex4386** [Alex4386/turnoff-namuwiki#37]
# 개선 사항

이슈를 무분별하게 생성하거나, 각각 이슈 하나씩 할당되어야 하는 내용을 하나의 이슈로 퉁 쳐서 올리는 경우가 있어, 해당 경우에 대한 기여자 이슈생성 가이드라인이 필요합니다.

[CONTRIBUTORS.md](https://github.com/Alex4386/turnoff-namuwiki/blob/master/CONTRIBUTORS.md) 의 개선이 필요할 것 같습니다.

**Comment by kweonsunho** [comment]
죄송합니다.
알기 쉽고 한 이슈당 하나씩 작성하겠습니다.

**Comment by Alex4386** [comment]
> 죄송합니다.
> 알기 쉽고 한 이슈당 하나씩 작성하겠습니다.

해당 경우를 위한 대비 케이스 작성입니다.

**Comment by Alex4386** [comment]
ISSUE Template 작성 완료. Closing Issue
