### ISSUE TITLE
[Bug] 페이지내 anchor 간 이동 중 자동 이동이 요청됨.

### ISSUE THREAD

**Issue by kweonsunho** [Alex4386/turnoff-namuwiki#38]
# ISSUE: Feature Request
## 추가를 원하는 기능이 무엇인가요? What kind of feature you are requesting?
- [ ] 논문 웹페이지 추가 지원 (more journal page support)  
- [ ] 나무위키 제거 검색엔진 추가 (more search result filters for Search Engine)  
- [ ] UX (사용자 경험) 개선 (User Experience Enhancements)
- [X] 그 외 (Others)  

## 어떤 기능을 추가했으면 좋을까요? (What feature you are requesting?)
**정확하게 설명해 주세요** (Please explain it in detail)
현재 리브레 위키와 위백의 페쳐 버전을 쓰고 있는데요, 각주를 누르거나, 문서의 목차에서 각 문단으로 가는 버튼을 눌러도 새 탭이 만들어지는 문제가 있습니다.

**Comment by Alex4386** [comment]
**제목은 이슈에 보고 하고자 하는 내용을 적으셔야 합니다.**  
**업로드 전 프리뷰 확인 후 마크업 오류가 있는 지 확인 후 올려주시기 바랍니다.**
**해당 사항은 버그로 FeatureRequest가 아닌 Bug 양식을 쓰셔야 합니다.**

**Comment by Alex4386** [comment]
https://github.com/Alex4386/turnoff-namuwiki/issues/29#issuecomment-629992455

> @kweonsunho
> 마크다운 문법에서 체크 박스 문법은
> 
> ```
> * [V]
> ```
> 
> 가 아닌
> 
> ```
> * [X]
> ```
> 
> 입니다.
> (띄어쓰기도 고려합니다, 붙여 써주세요.)
> 추후 이슈 생성시 적용 부탁드립니다.

**Comment by kweonsunho** [comment]
> [#29 (comment)](https://github.com/Alex4386/turnoff-namuwiki/issues/29#issuecomment-629992455)
> 
> > @kweonsunho
> > 마크다운 문법에서 체크 박스 문법은
> > ```
> > * [V]
> > ```
> > 
> > 
> > 가 아닌
> > ```
> > * [X]
> > ```
> > 
> > 
> > 입니다.
> > (띄어쓰기도 고려합니다, 붙여 써주세요.)
> > 추후 이슈 생성시 적용 부탁드립니다.

죄송합니다ㅠㅠ

**Comment by Alex4386** [comment]
> > [#29 (comment)](https://github.com/Alex4386/turnoff-namuwiki/issues/29#issuecomment-629992455)
> > > @kweonsunho
> > > 마크다운 문법에서 체크 박스 문법은
> > > ```
> > > * [V]
> > > ```
> > > 
> > > 
> > > 가 아닌
> > > ```
> > > * [X]
> > > ```
> > > 
> > > 
> > > 입니다.
> > > (띄어쓰기도 고려합니다, 붙여 써주세요.)
> > > 추후 이슈 생성시 적용 부탁드립니다.
> 
> 죄송합니다ㅠㅠ

죄송하기 보다는 더욱 빠른 개발을 위해서 협조해 주세요! :)

**Comment by kweonsunho** [comment]
> > > [#29 (comment)](https://github.com/Alex4386/turnoff-namuwiki/issues/29#issuecomment-629992455)
> > > > @kweonsunho
> > > > 마크다운 문법에서 체크 박스 문법은
> > > > ```
> > > > * [V]
> > > > ```
> > > > 
> > > > 
> > > > 가 아닌
> > > > ```
> > > > * [X]
> > > > ```
> > > > 
> > > > 
> > > > 입니다.
> > > > (띄어쓰기도 고려합니다, 붙여 써주세요.)
> > > > 추후 이슈 생성시 적용 부탁드립니다.
> > 
> > 
> > 죄송합니다ㅠㅠ
> 
> 죄송하기 보다는 알려드린 사항을 적용해서 이슈를 작성하여 더욱 빠른 개발을 위해서 협조해 주세요! :)

아! 그리고 뒤로가기 버튼을 눌러도 새로 나오는 버그가 있는데 이건 고치기 여렵겠네요 T.T

**Comment by kweonsunho** [comment]
> > > [#29 (comment)](https://github.com/Alex4386/turnoff-namuwiki/issues/29#issuecomment-629992455)
> > > > @kweonsunho
> > > > 마크다운 문법에서 체크 박스 문법은
> > > > ```
> > > > * [V]
> > > > ```
> > > > 
> > > > 
> > > > 가 아닌
> > > > ```
> > > > * [X]
> > > > ```
> > > > 
> > > > 
> > > > 입니다.
> > > > (띄어쓰기도 고려합니다, 붙여 써주세요.)
> > > > 추후 이슈 생성시 적용 부탁드립니다.
> > 
> > 
> > 죄송합니다ㅠㅠ
> 
> 죄송하기 보다는 알려드린 사항을 적용해서 이슈를 작성하여 더욱 빠른 개발을 위해서 협조해 주세요! :)

그리고  namu.wiki/w/고기처럼 직접 주소를 치면 다른 위키가 3번 나오는 문제가 있습니다.

**Comment by Alex4386** [comment]
> 아! 그리고 뒤로가기 버튼을 눌러도 새로 나오는 버그가 있는데 이건 고치기 여렵겠네요 T.T
> 그리고 namu.wiki/w/고기처럼 직접 주소를 치면 다른 위키가 3번 나오는 문제가 있습니다.

3번 이상 경고 하였기 때문에 해당 코멘트는 삭제 조치 하겠습니다.  
**이슈 하나 당 버그 수정/기능 추가 하나씩 입니다.**

**Comment by kweonsunho** [comment]
ㄴ

> > 아! 그리고 뒤로가기 버튼을 눌러도 새로 나오는 버그가 있는데 이건 고치기 여렵겠네요 T.T
> > 그리고 namu.wiki/w/고기처럼 직접 주소를 치면 다른 위키가 3번 나오는 문제가 있습니다.
> 
> 3번 이상 경고 하였기 때문에 해당 코멘트는 삭제 조치 하겠습니다.
> **이슈 하나 당 버그 수정/기능 추가 하나씩 입니다.**

그러면 저 이슈는 따로 올릴까요?
그럴 필요 없나요?

**Comment by Alex4386** [comment]
> ㄴ
> 
> > > 아! 그리고 뒤로가기 버튼을 눌러도 새로 나오는 버그가 있는데 이건 고치기 여렵겠네요 T.T
> > > 그리고 namu.wiki/w/고기처럼 직접 주소를 치면 다른 위키가 3번 나오는 문제가 있습니다.
> > 
> > 
> > 3번 이상 경고 하였기 때문에 해당 코멘트는 삭제 조치 하겠습니다.
> > **이슈 하나 당 버그 수정/기능 추가 하나씩 입니다.**
> 
> 그러면 저 이슈는 따로 올릴까요?
> 그럴 필요 없나요?

Agile Development 의 목적은 각각 오류/기능의 수정 사항 및 기능 구현 사항을 독립적으로 처리하기 위함입니다.  
당연히 이슈를 각각 생성 하셔야 합니다.

**Comment by Alex4386** [comment]
onUpdate 함수 특성상 기존 URL 을 가져오지 못합니다. 따라서 같은 문서내에서도 URL 변경시 (ex. 문서 내 anchor 이동의 경우에는 처리가 어렵습니다. 구현이 가능한경우 PR 바랍니다.)

**Comment by kweonsunho** [comment]
> onUpdate 함수 특성상 기존 URL 을 가져오지 못합니다. 따라서 같은 문서내에서도 URL 변경시 (ex. 문서 내 anchor 이동의 경우에는 처리가 어렵습니다. 구현이 가능한경우 PR 바랍니다.)

문서 문단의 경우에는 %s=*.* 이렇게 되니까 할 수 있지 않나요"

**Comment by kweonsunho** [comment]
> onUpdate 함수 특성상 기존 URL 을 가져오지 못합니다. 따라서 같은 문서내에서도 URL 변경시 (ex. 문서 내 anchor 이동의 경우에는 처리가 어렵습니다. 구현이 가능한경우 PR 바랍니다.)

그리고 각주를 눌렀을 때는 
#fn-*처럼 되네요

**Comment by Alex4386** [comment]
아니요. 해당 연결이 외부에서 저러한 모양으로 직접 접근 한 것인지. 아니면 나무위키 내부에서 다시 접근 한 것인지 알 수가 없습니다.

**Comment by kweonsunho** [comment]
> 아니요. 해당 연결이 외부에서 저러한 모양으로 직접 접근 한 것인지. 아니면 나무위키 내부에서 다시 접근 한 것인지 알 수가 없습니다.

어쩌피 별 상관 없지 않나요? 그 문단이 있는지 없는지도 알 수 없는데...

**Comment by kweonsunho** [comment]
> 아니요. 해당 연결이 외부에서 저러한 모양으로 직접 접근 한 것인지. 아니면 나무위키 내부에서 다시 접근 한 것인지 알 수가 없습니다.

**Comment by kweonsunho** [comment]
> 아니요. 해당 연결이 외부에서 저러한 모양으로 직접 접근 한 것인지. 아니면 나무위키 내부에서 다시 접근 한 것인지 알 수가 없습니다.

이 이슈는 현재 처리 되었나요?

**Comment by Alex4386** [comment]
> > 아니요. 해당 연결이 외부에서 저러한 모양으로 직접 접근 한 것인지. 아니면 나무위키 내부에서 다시 접근 한 것인지 알 수가 없습니다.
> 
> 이 이슈는 현재 처리 되었나요?

BrowserExtensions Specification 문제입니다. 해당 이유로 이 이슈에 [structural issue] 태그가 붙어있습니다.

**Comment by Alex4386** [comment]
> > 아니요. 해당 연결이 외부에서 저러한 모양으로 직접 접근 한 것인지. 아니면 나무위키 내부에서 다시 접근 한 것인지 알 수가 없습니다.
> 
> 어쩌피 별 상관 없지 않나요? 그 문단이 있는지 없는지도 알 수 없는데...

다시 한번 생각해 보시기 바랍니다.
문단 내에서 이동 할때에는.

`https://namu.wiki/w/문서` -> `https://namu.wiki/w/문서#어쩌구` 이러한 형식으로 이루어 지게 됩니다.  

저 형식의 URL은 해당 URL의 anchor 를 지칭할때 주로 사용됩니다. (HTML Specs 확인 바람)  

그러나 BrowserExtensions의 onUpdated의 경우, 해당 문서의 URL이 변경되는 경우 무조건 호출 되게 됩니다.  
현재 구현체는 onUpdate event를 받으면 접속 대상 URL이 namu.wiki 또는 기타 미러인지 정규식을 통해 확인 하고, 문서 명을 URL에서 읽어 리다이렉트하는 방식입니다.  

만일 @kweonsunho 님이 지칭한 바와 같이, 뒤에 anchor 부분에 해당 하는 것이 존재할 때 리다이렉트를 막을 경우, 해당 방식으로 제시된 URL은 리다이렉트가 되지 않게 됩니다.

**Comment by Alex4386** [comment]
여기서 문제가 발생합니다.  

anchor 가 존재하는 만 확인하고 리다이렉트 여부를 막는 경우, 정상적으로 # 를 이용한 링크,  
예) `https://github.com/Alex4386/turnoff-namuwiki/issues/38#issuecomment-632839079` 에서는 사용 할 수 없게 됩니다.  

제가 개인 과외 강사는 아니므로, 직접 URL Specs 를 찾아보시는 것을 권장합니다. # 은 해당 부분을 지칭할때 사용하는 Locator 의 일부이지 나무위키에서만 사용하는 문단 표기용 시스템이 아닙니다.  

또한, 해당 형식으로 링크된 경우가 당장 나무위키 내에서도 많기에, 문단 대상으로 링크된 내용을 모두 리다이렉션 차단 하는 것은 불가능 합니다.

**Comment by kweonsunho** [comment]
> 
> 
> 여기서 문제가 발생합니다.
> 
> anchor 가 존재하는 만 확인하고 리다이렉트 여부를 막는 경우, 정상적으로 # 를 이용한 링크,
> 예) `https://github.com/Alex4386/turnoff-namuwiki/issues/38#issuecomment-632839079` 형식의 나무위키 링크에서는 리다이렉션을 사용 할 수 없게 됩니다.
> 
> 제가 개인 과외 강사는 아니므로, 직접 URL Specs 를 찾아보시는 것을 권장합니다. # 은 해당 부분을 지칭할때 사용하는 Locator 의 일부이지 나무위키에서만 사용하는 문단 표기용 시스템이 아닙니다.
> 
> 또한, 해당 형식으로 링크된 경우가 당장 나무위키 내에서도 많기에, 문단 대상으로 링크된 내용을 모두 리다이렉션 차단 하는 것은 불가능 합니다.

그러면 나무위키에서 정상적인 넘겨주기가 필요한데 # 같은 링크를 쓰는 것이 있나요?

**Comment by Alex4386** [comment]
네, 해당 문서 내 이동을 브라우저에서 문서 이동으로 간주해서 생기는 문제입니다.

그렇기에 맥락 인지가 필요합니다.

**Comment by kweonsunho** [comment]
> 네, 해당 문서 내 이동을 브라우저에서 문서 이동으로 간주해서 생기는 문제입니다.
> 
> 그렇기에 맥락 인지가 필요합니다.

아... #이 있는지만 알 수 있고 # 뒤에 뭐가 오는 지는 알 수 없어서 일어나는 현상이죠?

**Comment by kweonsunho** [comment]
그러면 나무위키 링크에서 각주로 넘겨주는 문서는 없으므로 각주는 다 차단해도 될 것 같은데요...
문단은 링크 달 때 문단 선택해서 넘겨 줄 수 있느니까 그렇다치고...

**Comment by Alex4386** [comment]
> 그러면 나무위키 링크에서 각주로 넘겨주는 문서는 없으므로 각주는 다 차단해도 될 것 같은데요...
> 문단은 링크 달 때 문단 선택해서 넘겨 줄 수 있느니까 그렇다치고...

아뇨. 외부에서 문단을 대상으로 링크하는 경우가 있습니다.

**Comment by kweonsunho** [comment]
> > 그러면 나무위키 링크에서 각주로 넘겨주는 문서는 없으므로 각주는 다 차단해도 될 것 같은데요...
> > 문단은 링크 달 때 문단 선택해서 넘겨 줄 수 있느니까 그렇다치고...
> 
> 아뇨. 외부에서 문단을 대상으로 링크하는 경우가 있습니다.
> 각주와 문단의 원리가 동일하기에 따로 구분하는 것이 의미가 없습니다.

그게 아니라 문단은 #s-숫자 고 각주는 #fn-숫자니까 # 뒤에 오는 걸로 구분할 수 있지 않나요?

**Comment by Alex4386** [comment]
> > > 그러면 나무위키 링크에서 각주로 넘겨주는 문서는 없으므로 각주는 다 차단해도 될 것 같은데요...
> > > 문단은 링크 달 때 문단 선택해서 넘겨 줄 수 있느니까 그렇다치고...
> > 
> > 
> > 아뇨. 외부에서 문단을 대상으로 링크하는 경우가 있습니다.
> > 각주와 문단의 원리가 동일하기에 따로 구분하는 것이 의미가 없습니다.
> 
> 그게 아니라 문단은 #s-숫자 고 각주는 #fn-숫자니까 # 뒤에 오는 걸로 구분할 수 있지 않나요?

다시 말씀드리지만, 각주로 콜하는 경우 리다이렉트를 하지 말라는 행위는 주석으로 직접 링크된 URL에 대한 리다이렉션 방지이므로 원래 목적인 나무위키 접속시 리다이렉트 라는 피쳐를 Break 하는 행위입니다.  정말 필요한 사항인지 고려가 필요할 것 같습니다.

**Comment by Alex4386** [comment]
> > > 아니요. 해당 연결이 외부에서 저러한 모양으로 직접 접근 한 것인지. 아니면 나무위키 내부에서 다시 접근 한 것인지 알 수가 없습니다.
> > 
> > 
> > 이 이슈는 현재 처리 되었나요?
> 
> BrowserExtensions Specification 문제입니다. 해당 이유로 이 이슈에 [structural issue] 태그가 붙어있습니다.

이 이슈를 해결해 볼 수 있는 방안을 찾았으나 Potential Memory Leak 문제가 발생 할 수 있을 것이라고 생각됩니다.
https://stackoverflow.com/a/33771228/8034896

**Comment by kweonsunho** [comment]
> > > > 그러면 나무위키 링크에서 각주로 넘겨주는 문서는 없으므로 각주는 다 차단해도 될 것 같은데요...
> > > > 문단은 링크 달 때 문단 선택해서 넘겨 줄 수 있느니까 그렇다치고...
> > > 
> > > 
> > > 아뇨. 외부에서 문단을 대상으로 링크하는 경우가 있습니다.
> > > 각주와 문단의 원리가 동일하기에 따로 구분하는 것이 의미가 없습니다.
> > 
> > 
> > 그게 아니라 문단은 #s-숫자 고 각주는 #fn-숫자니까 # 뒤에 오는 걸로 구분할 수 있지 않나요?
> 
> 다시 말씀드리지만, 각주로 콜하는 경우 리다이렉트를 하지 말라는 행위는 주석으로 직접 링크된 URL에 대한 리다이렉션 방지이므로 원래 목적인 나무위키 접속시 리다이렉트 라는 피쳐를 Break 하는 행위입니다. 정말 필요한 사항인지 고려가 필요할 것 같습니다.

솔직히 나무위키 링크를 각주까지 붙여가며 들어가는 사람이 어딨습니까? 그리고 어쩌피 한 문서당 하나씩 리다이렉트만 하면 되지 않나요?

**Comment by Alex4386** [comment]
> 솔직히 나무위키 링크를 각주까지 붙여가며 들어가는 사람이 어딨습니까? 그리고 어쩌피 한 문서당 하나씩 리다이렉트만 하면 되지 않나요?

원래 프로그래밍을 할 때에는 모든 Edge case 에 대응하는 것이 맞습니다.  
각주까지 붙여서 직접 URL로 들어가는 경우는 없겠지만, URL에 주석이 붙은 상태에서 하이퍼링크가 걸려있는 상황이라면 충분히 가능성이 있다고 생각합니다.  

또한, turnoff-namuwiki의 목적은 정확한 정보로의 이동이 목표이므로, 리다이렉트가 오진되어 아예 리다이렉트가 전혀 되지 않는 상황보다는 되는 상황으로 목표하는 것이 적절하다고 생각합니다.

**Comment by kweonsunho** [comment]
> > 솔직히 나무위키 링크를 각주까지 붙여가며 들어가는 사람이 어딨습니까? 그리고 어쩌피 한 문서당 하나씩 리다이렉트만 하면 되지 않나요?
> 
> 원래 프로그래밍을 할 때에는 모든 Edge case 에 대응하는 것이 맞습니다.
> 각주까지 붙여서 직접 URL로 들어가는 경우는 없겠지만, URL에 주석이 붙은 상태에서 하이퍼링크가 걸려있는 상황이라면 충분히 가능성이 있다고 생각합니다.
> 
> 또한, turnoff-namuwiki의 목적은 정확한 정보로의 이동이 목표이므로, 리다이렉트가 오진되어 아예 리다이렉트가 전혀 되지 않는 상황보다는 되는 상황으로 목표하는 것이 적절하다고 생각합니다.
그러면 일단 #뒤를 다 막을 버전을 제 포크 버전에 PR해주실 수 있나요?

**Comment by Alex4386** [comment]
> > > 솔직히 나무위키 링크를 각주까지 붙여가며 들어가는 사람이 어딨습니까? 그리고 어쩌피 한 문서당 하나씩 리다이렉트만 하면 되지 않나요?
> > 
> > 
> > 원래 프로그래밍을 할 때에는 모든 Edge case 에 대응하는 것이 맞습니다.
> > 각주까지 붙여서 직접 URL로 들어가는 경우는 없겠지만, URL에 주석이 붙은 상태에서 하이퍼링크가 걸려있는 상황이라면 충분히 가능성이 있다고 생각합니다.
> > 또한, turnoff-namuwiki의 목적은 정확한 정보로의 이동이 목표이므로, 리다이렉트가 오진되어 아예 리다이렉트가 전혀 되지 않는 상황보다는 되는 상황으로 목표하는 것이 적절하다고 생각합니다.
> 
> 그러면 일단 #뒤를 다 막을 버전을 제 포크 버전에 PR해주실 수 있나요?

죄송하지만 저는 @kweonsunho 님의 SI가 아닙니다.

**Comment by Alex4386** [comment]
> 그러면 일단 #뒤를 다 막을 버전을 제 포크 버전에 PR해주실 수 있나요?

또한 저는 이렇게 구현할 생각이 없으며, https://stackoverflow.com/a/33771228/8034896 에서 제시한 context 임시 저장 방법을 이용하여 구현할 생각이므로, 원하시는 대로 구현하고 싶으신 경우 본인이 직접 해주시기 바랍니다.

**Comment by kweonsunho** [comment]
> > 그러면 일단 #뒤를 다 막을 버전을 제 포크 버전에 PR해주실 수 있나요?
> 
> 또한 저는 이렇게 구현할 생각이 없으며, https://stackoverflow.com/a/33771228/8034896 에서 제시한 context 임시 저장 방법을 이용하여 구현할 생각이므로, 원하시는 대로 구현하고 싶으신 경우 본인이 직접 해주시기 바랍니다.

어떻게는 해결을 하겠다는 건가요?

**Comment by kweonsunho** [comment]
> > 그러면 일단 #뒤를 다 막을 버전을 제 포크 버전에 PR해주실 수 있나요?
> 
> 또한 저는 이렇게 구현할 생각이 없으며, https://stackoverflow.com/a/33771228/8034896 에서 제시한 context 임시 저장 방법을 이용하여 구현할 생각이므로, 원하시는 대로 구현하고 싶으신 경우 본인이 직접 해주시기 바랍니다.

그러면 구현 관련 질문 하나만 하겠습니다. 
 if (searchQuery && !/^(나무위키|파일|분류|틀):.+/.test(searchQuery)) {
여기를 좀 바꾸면 될 것 같은데 어떻게 바꿔야 할까요?

**Comment by Alex4386** [comment]
> 그러면 구현 관련 질문 하나만 하겠습니다.
> if (searchQuery && !/^(나무위키|파일|분류|틀):.+/.test(searchQuery)) {
> 여기를 좀 바꾸면 될 것 같은데 어떻게 바꿔야 할까요?

GitHub Issues는 질문 게시판이 아닙니다!!!

**Comment by Alex4386** [comment]
> > > 그러면 일단 #뒤를 다 막을 버전을 제 포크 버전에 PR해주실 수 있나요?
> > 
> > 
> > 또한 저는 이렇게 구현할 생각이 없으며, https://stackoverflow.com/a/33771228/8034896 에서 제시한 context 임시 저장 방법을 이용하여 구현할 생각이므로, 원하시는 대로 구현하고 싶으신 경우 본인이 직접 해주시기 바랍니다.
> 
> 그러면 구현 관련 질문 하나만 하겠습니다.
> if (searchQuery && !/^(나무위키|파일|분류|틀):.+/.test(searchQuery)) {
> 여기를 좀 바꾸면 될 것 같은데 어떻게 바꿔야 할까요?

또한 자신의 포크판 코드 수정을 업스트림 개발자에게 요청하는 것은... 상당히 타당한 태도가 아닌 것 같습니다.

**Comment by kweonsunho** [comment]
> > > > 그러면 일단 #뒤를 다 막을 버전을 제 포크 버전에 PR해주실 수 있나요?
> > > 
> > > 
> > > 또한 저는 이렇게 구현할 생각이 없으며, https://stackoverflow.com/a/33771228/8034896 에서 제시한 context 임시 저장 방법을 이용하여 구현할 생각이므로, 원하시는 대로 구현하고 싶으신 경우 본인이 직접 해주시기 바랍니다.
> > 
> > 
> > 그러면 구현 관련 질문 하나만 하겠습니다.
> > if (searchQuery && !/^(나무위키|파일|분류|틀):.+/.test(searchQuery)) {
> > 여기를 좀 바꾸면 될 것 같은데 어떻게 바꿔야 할까요?
> 
> 또한 자신의 포크판 코드 수정을 업스트림 개발자에게 요청하는 것은... 상당히 타당한 태도가 아닌 것 같습니다.

그러면 어느 부분을 수정해야 하는지만 알려 주세요

**Comment by kweonsunho** [comment]
> > > > 그러면 일단 #뒤를 다 막을 버전을 제 포크 버전에 PR해주실 수 있나요?
> > > 
> > > 
> > > 또한 저는 이렇게 구현할 생각이 없으며, https://stackoverflow.com/a/33771228/8034896 에서 제시한 context 임시 저장 방법을 이용하여 구현할 생각이므로, 원하시는 대로 구현하고 싶으신 경우 본인이 직접 해주시기 바랍니다.
> > 
> > 
> > 그러면 구현 관련 질문 하나만 하겠습니다.
> > if (searchQuery && !/^(나무위키|파일|분류|틀):.+/.test(searchQuery)) {
> > 여기를 좀 바꾸면 될 것 같은데 어떻게 바꿔야 할까요?
> 
> 또한 자신의 포크판 코드 수정을 업스트림 개발자에게 요청하는 것은... 상당히 타당한 태도가 아닌 것 같습니다.

그러면 어디다 물어 봅니까?

**Comment by kweonsunho** [comment]
물어볼 좋은 곳을 알려 주세요.

**Comment by Alex4386** [comment]
> 그러면 어디다 물어 봅니까?
아시다시피 저는 turnoff-namuwiki를 개발을 해서 돈을 받거나 이것이 제 직업이 아닙니다.  
따라서 응답이 늦어지거나 기능 개발이 늦어지는 것은 어쩔수 없습니다. 양해 부탁드립니다.

애초에 포크판은 자신이 코드를 더욱 개선하기 위해 업스트림의 코드를 따와서 나만의 버전을 만드는 것입니다.
또한 라이선스 상에서 저는 이 코드의 WARRANTY를 제공하지 않는다고 명시 되어있으므로, *FM대로라면, 본인이 코드를 읽고 이해 하신 후 추가 하시는 것이 맞습니다.* 비매너 행위라고 말하는 이유는 애초에 업스트림 메인테이너가 구현이 가능한 사항이라면 업스트림 메인테이너가 업스트림에 추가하는 것이 적절하지, 포크판에 커밋하는 사항은 거의 없습니다. 애초에 hierarchy 형태의 구조이기 때문이죠.

그러나 오픈소스 커뮤니티 활성화 및 기여자 확대를 위해 질문을 허용하고 있습니다. Issues는 코드상의 문제/버그/기능추가를 추적하는 목적이므로, 질문을 받는 목적으로는 적절하지 않습니다.

따라서 저는 README.md 에 디스코드 커뮤니티의 링크를 개설해 두었고, 제 개인 메일 주소를 깃허브 프로필에 명시해 두었습니다. 해당 두 장소를 이용해 주시면 됩니다.

**Comment by kweonsunho** [comment]
> > 그러면 어디다 물어 봅니까?
> 
> 아시다시피 저는 turnoff-namuwiki를 개발을 해서 돈을 받거나 이것이 제 직업이 아닙니다.
> 따라서 응답이 늦어지거나 기능 개발이 늦어지는 것은 어쩔수 없습니다. 양해 부탁드립니다.
> 
> 애초에 포크판은 자신이 코드를 더욱 개선하기 위해 업스트림의 코드를 따와서 나만의 버전을 만드는 것입니다.
> 또한 라이선스 상에서 저는 이 코드의 WARRANTY를 제공하지 않는다고 명시 되어있으므로, _FM대로라면, 본인이 코드를 읽고 이해 하신 후 추가 하시는 것이 맞습니다._ 비매너 행위라고 말하는 이유는 애초에 업스트림 메인테이너가 구현이 가능한 사항이라면 업스트림 메인테이너가 업스트림에 추가하는 것이 적절하지, 포크판에 커밋하는 사항은 거의 없습니다. 애초에 hierarchy 형태의 구조이기 때문이죠.
> 
> 그러나 오픈소스 커뮤니티 활성화 및 기여자 확대를 위해 질문을 허용하고 있습니다. Issues는 코드상의 문제/버그/기능추가를 추적하는 목적이므로, 질문을 받는 목적으로는 적절하지 않습니다.
> 
> 따라서 저는 README.md 에 디스코드 커뮤니티의 링크를 개설해 두었고, 제 개인 메일 주소를 깃허브 프로필에 명시해 두었습니다. 해당 두 장소를 이용해 주시면 됩니다.

넵.

**Comment by Alex4386** [comment]
이 이슈는 아직 해결되지 않은 이슈이므로 여는 것이 맞습니다.

**Comment by Alex4386** [comment]
이슈 해결 완료.
