### ISSUE TITLE
[Bug] 파일:*** 문서의 리다이렉트 현상 발생

### ISSUE THREAD

**Issue by kweonsunho** [Alex4386/turnoff-namuwiki#39]
# ISSUE: Feature Request
## 추가를 원하는 기능이 무엇인가요? What kind of feature you are requesting?
- [ ] 논문 웹페이지 추가 지원 (more journal page support)  
- [ ] 나무위키 제거 검색엔진 추가 (more search result filters for Search Engine)  
- [ ] UX (사용자 경험) 개선 (User Experience Enhancements)
- [X] 그 외 (Others)  
파일:XXX문서도 다른 위키 문서로 이동되는 문제가 있습니다.
## 어떤 기능을 추가했으면 좋을까요? (What feature you are requesting?)
**정확하게 설명해 주세요** (Please explain it in detail)

**Comment by Alex4386** [comment]
**해당 사항은 버그에 해당합니다. 버그 카테고리로 설정해 주세요.**

**Comment by kweonsunho** [comment]
> **해당 사항은 버그에 해당합니다. 버그 카테고리로 설정해 주세요.**

죄송합니다. 순간적으로ㅠㅠ1초만에ㅠㅠ

**Comment by Alex4386** [comment]
> > **해당 사항은 버그에 해당합니다. 버그 카테고리로 설정해 주세요.**
> 
> 죄송합니다. 순간적으로ㅠㅠ1초만에ㅠㅠ

이슈를 만들 때는 신중하게 만들어 주세요. 이슈 하나 만들면 개발자한테 알림이 옵니다.

**Comment by kweonsunho** [comment]
> > > **해당 사항은 버그에 해당합니다. 버그 카테고리로 설정해 주세요.**
> > 
> > 
> > 죄송합니다. 순간적으로ㅠㅠ1초만에ㅠㅠ
> 
> 이슈를 만들 때는 신중하게 만들어 주세요. 이슈 하나 만들면 개발자한테 알림이 옵니다.

네ㅠ죄송합니다ㅠㅠ

**Comment by Alex4386** [comment]
이슈 해결됨. 종료.
