### ISSUE TITLE
[Feature Request] 나무위키의 하위 문서에 대한 리다이렉션 방안

### ISSUE THREAD

**Issue by kweonsunho** [Alex4386/turnoff-namuwiki#40]
# ISSUE: Feature Request
## 추가를 원하는 기능이 무엇인가요? What kind of feature you are requesting?
- [ ] 논문 웹페이지 추가 지원 (more journal page support)  
- [ ] 나무위키 제거 검색엔진 추가 (more search result filters for Search Engine)  
- [ ] UX (사용자 경험) 개선 (User Experience Enhancements)
- [X] 그 외 (Others)  

## 어떤 기능을 추가했으면 좋을까요? (What feature you are requesting?)
**정확하게 설명해 주세요** (Please explain it in detail)
고기/좋은 점 같이 /이 들어가는 문서도 리다이렉트 대상에서 빼야 될 것 같습니다.
이런 것은 다른 위키에 있는 경우가 적습니다.
그리고 제가 리브레위키도 지원하는 버전을 따로 스토어에 올렸는데 괜찮나요?

**Comment by Alex4386** [comment]
하단 저작권 문구 상에서 **Fork**임을 명시 바랍니다.

**Comment by Alex4386** [comment]
**Breaking Changes** 로 분류되므로 다른 메인테이너분들의 의견을 들어야 할 것 같습니다.
@park012241

**Comment by park012241** [comment]
intelliBan 룰을 만들 수 있게 하거나 토글할 수 있으면 좋을 것 같습니다.
원래의 목적인 나무위키 차단은 그대로 할 수 있어야 할 것 같네요.

논문 목적으로 쓰는 사람도 있지만, 일하는중에 방해받지 않기 위해 켜는 사람도 있습니다. (접니다)

**Comment by park012241** [comment]
사실 하위 문서의 경우 흔하게 사용됩니다
그러나 하위문서를 어떻게 리다이렉트 해야할지가 의문이네요

단순히 "뫄뫄/좋은점"을 가지고 어떻게 리다이렉트 해야 사람들이 만족할까요!

**Comment by kweonsunho** [comment]
> 
> 
> > 그리고 제가 리브레위키도 지원하는 버전을 따로 스토어에 올렸는데 괜찮나요?
> 
> 하단 저작권 문구 상에서 **Fork**임을 명시 바랍니다.
> 
> ![image](https://user-images.githubusercontent.com/27724108/82697174-5ea9a580-9ca3-11ea-83a2-876743a2f622.png)

네 조속한 수정을 하겠습니다.

**Comment by kweonsunho** [comment]
"제 말은 뫄뫄/좋은점 같이 하위 문서가 다른 위키에도 있을 가능성은 적으니 그것은 리다이렉트 시키지 말자" 라는 의견인데요?

**Comment by Alex4386** [comment]
> "제 말은 뫄뫄/좋은점 같이 하위 문서가 다른 위키에도 있을 가능성은 적으니 그것은 리다이렉트 시키지 말자" 라는 의견인데요?

해당 의견 보다는 -> 뫄뫄 로 리다이렉트 하는 것이 더 나은 것 같습니다.

**Comment by kweonsunho** [comment]
> 
> 
> > "제 말은 뫄뫄/좋은점 같이 하위 문서가 다른 위키에도 있을 가능성은 적으니 그것은 리다이렉트 시키지 말자" 라는 의견인데요?
> 
> 해당 의견 보다는 -> 뫄뫄 로 리다이렉트 하는 것이 더 나은 것 같습니다.

오 그것도 좋은 생각인데요!

**Comment by kweonsunho** [comment]
> 
> 
> > 그리고 제가 리브레위키도 지원하는 버전을 따로 스토어에 올렸는데 괜찮나요?
> 
> 하단 저작권 문구 상에서 **Fork**임을 명시 바랍니다.
> 
> ![image](https://user-images.githubusercontent.com/27724108/82697174-5ea9a580-9ca3-11ea-83a2-876743a2f622.png)

https://github.com/kweonsunho/turnoff-namuwiki/blob/master/interface/popup/index.html
수정 마쳤습니다.

**Comment by kweonsunho** [comment]
언제 해결되나요?

**Comment by Alex4386** [comment]
> 언제 해결되나요?

저는 이 프로젝트가 제 직업이 아닙니다. 급하시다면 PR 부탁드립니다.

**Comment by Alex4386** [comment]
이슈 해결 완료
