### ISSUE TITLE
[Feature Request] 미러 사이트 mirror.wiki 검색 결과 숨기기

### ISSUE THREAD

**Issue by thegreatseo** [Alex4386/turnoff-namuwiki#48]
# ISSUE: Feature Request
## 추가를 원하는 기능이 무엇인가요? What kind of feature you are requesting?
- [ ] 논문 웹페이지 추가 지원 (more journal page support)  
- [ ] 나무위키 제거 검색엔진 추가 (more search result filters for Search Engine)  
- [ ] UX (사용자 경험) 개선 (User Experience Enhancements)
- [-] 그 외 (Others)  

## 어떤 기능을 추가했으면 좋을까요? (What feature you are requesting?)
미러 차단 기능을 켰지만 구글 검색 결과에 mirror.wiki 가 보입니다. 미러 차단 기능은 어떤 사이트를 숨기는 기능인가요? 나무위키 미러인 mirror.wiki, 그리고 덤프 사이트인 thewiki.kr 도 숨길 수 있었으면 좋겠습니다.

**Comment by Alex4386** [comment]
감사합니다. 다음 버전에 추가 하겠습니다.

**Comment by Alex4386** [comment]
혹시 기능을 원하시는 경우 잠시 후 커밋뒤에 구동되는 GitHub Actions의 zip 파일의 수동 설치를 통해 사용이 가능합니다.

**Comment by Alex4386** [comment]
> 미러 차단 기능을 켰지만 구글 검색 결과에 mirror.wiki 가 보입니다. 미러 차단 기능은 어떤 사이트를 숨기는 기능인가요? 나무위키 미러인 mirror.wiki, 그리고 덤프 사이트인 thewiki.kr 도 숨길 수 있었으면 좋겠습니다.

네, 해당 기능은 mirror.wiki 및 thewiki.kr 등의 덤프사이트 차단 목적이 맞습니다.

**Comment by Alex4386** [comment]
Issue Resolved 로 이슈를 닫겠습니다.
