### ISSUE TITLE
새 릴리즈 요청

### ISSUE THREAD

**Issue by saschanaz** [Alex4386/turnoff-namuwiki#63]
아직까지 덕덕고 필터링이 되지 않아서 버그 고친 릴리즈 부탁드립니다 🙇‍♀️

**Comment by Alex4386** [comment]
Deploy 완료:

* Firefox: 적용 완료. 빠른 업데이트를 위해서는 삭제후 재설치가 필요합니다.
* Chrome: 심사 요청 완료. 대략 2-3일 소요 예정입니다.
* Whale: 심사요청 완료. 대략 4-5일 소요 예정입니다.

**Comment by saschanaz** [comment]
감사합니다! (삭제후 재설치하지 않아도 about:addons에서 업데이트 가능합니다 😆)
