### ISSUE TITLE
[Feature Request] Add newliweb

### ISSUE THREAD

**Issue by piquark6046** [Alex4386/turnoff-namuwiki#84]
# ISSUE: Feature Request
## 추가를 원하는 기능이 무엇인가요? What kind of feature you are requesting?
- [ ] 논문 웹페이지 추가 지원 (more journal page support)  
- [ ] 나무위키 제거 검색엔진 추가 (more search result filters for Search Engine)  
- [ ] UX (사용자 경험) 개선 (User Experience Enhancements)
- [X] 그 외 (Others)  

## 어떤 기능을 추가했으면 좋을까요? (What feature you are requesting?)
**정확하게 설명해 주세요** (Please explain it in detail)

umanle S.R.L. started a community service[^1] because an administrator of Ruliweb abused of their permission[^2].

[^1]: https://newliweb.com/
[^2]: https://bbs.ruliweb.com/best/board/300143/read/57777339

**Comment by Alex4386** [comment]
![image](https://github.com/Alex4386/turnoff-namuwiki/assets/27724108/f66f454a-61d1-4a35-a712-d842f88dab91)

추가 완료. `feature/manifestv3` 에서 트래킹 중.
