### ISSUE TITLE
[Bug] Doesn't work at Google Image Section (구글 이미지에서 작동하지 않음)

### ISSUE THREAD

**Issue by NangmanGureum** [Alex4386/turnoff-namuwiki#91]
## 환경 (Tell me the environments when the bug occurs)
* [ ] Google Chrome (or Chromium)  
* [ ] NAVER Whale Browser, Microsoft Edge (or Legacy Chromium)
* [x] Mozilla Firefox
* [ ] Mozilla Firefox for Android

### 가능하다면 버전을 적어주세요 (What is your browser's version)

125.0.3 (64-bit)
at Windows 11

## 버그에 대해 설명해 주세요 (Describe the bug)
Doesn't work block images from namu.wiki at Google's Image Section
구글 이미지 부분에서 나무위키에서 온 이미지가 차단이 되지 않습니다.

## 버그를 일으키는 방법에 대해서 설명해 주세요 (Please explain the steps to reproduce)
1. Search something at Google (like, "아인슈타인", which means "Einstein")
1. Click on 'Image' (In Korean, '이미지')
1. See the error

---

1. 구글에서 아무거나 검색합니다. (예: "아인슈타인")
1. '이미지'를 클릭합니다.
1. 에러를 확인합니다.

## 어떻게 동작해야 했나요? (What was the expected behavior?)
The picture in namu.wiki should not be visible. However, as you can see in the screenshot below, the picture is visible even though that plug-in is working.

나무위키에서 불러온 이미지가 보이지 않아야 합니다. 그러나, 아래의 스크린샷에서 보시다시피, 플러그인이 동작하고 있음에도 불구하고 나무위키에서의 이미지가 보입니다.

## 스크린샷 (Screenshots)
![image](https://github.com/Alex4386/turnoff-namuwiki/assets/23521834/31b8f20d-9751-4129-a5a4-8970cb64f1e6)

**Comment by Alex4386** [comment]
늦어서 죄송합니다.
현재 ManifestV3 마이그레이션 관련해서 현재 바로 스토어 적용은 어려울것 같습니다.

추후 코드 전환 작업 후 팔로우업드릴께요!

**Comment by Alex4386** [comment]
![image](https://github.com/Alex4386/turnoff-namuwiki/assets/27724108/9222a7a9-6295-4550-91de-1c37b1cef4a9)

제거 구현 완료 `feature/manifestv3`
